# DataFrames III: Data Extraction

In [1]:
import pandas as pd

## This Module's Dataset
- This module's dataset is a collection of all James Bond movies.

In [5]:
bond = pd.read_csv("jamesbond.csv")
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

## The set_index and reset_index Methods
- The index serves as the collection of primary identifiers/labels/entrypoints for the rows.
- The fastest way to extract a row is from a sorted index by position/label.
- Pandas uses index labels/values when merging different objects together.
- The `set_index` method sets an existing column as the index of the **DataFrame**.
- The `reset_index` method sets the standard ascending numeric index as the index of the **DataFrame**.

In [7]:
bond.set_index("Film").head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [10]:
bond.reset_index()
bond.reset_index(drop=True).head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [11]:
bond.set_index("Year").head()

,Film,Actor,Director,Box Office,Budget,Bond Actor Salary
Year,,,,,,
1962,Dr. No,Sean Connery,Terence Young,448.8,7.0,0.6
1963,From Russia with Love,Sean Connery,Terence Young,543.8,12.6,1.6
1964,Goldfinger,Sean Connery,Guy Hamilton,820.4,18.6,3.2
1965,Thunderball,Sean Connery,Terence Young,848.1,41.9,4.7
1967,Casino Royale,David Niven,Ken Hughes,315.0,85.0,NaN

## Retrieve Rows by Index Position with iloc Accessor
- The `iloc` accessor retrieves one or more rows by index position.
- Provide a pair of square brackets after the accessor.
- `iloc` accepts single values, lists, and slices.

In [13]:
bond = pd.read_csv("jamesbond.csv")
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [19]:
bond.iloc[5]
bond.iloc[[15,20]]
bond.iloc[4:8]
bond.iloc[0:6]
bond.iloc[:6]
bond.iloc[20:]

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
26,No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

## Retrieve Rows by Index Label with loc Accessor
- The `loc` accessor retrieves one or more rows by index label.
- Provide a pair of square brackets after the accessor.

In [21]:
bond = pd.read_csv("jamesbond.csv", index_col= "Film")
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [ ]:
bond.loc["Goldfinger"]
bond.loc["Casino Royale"]

bond.loc[["Octopussy","Moonraker"]]
bond.loc["Octopussy":].head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1

## Second Arguments to loc and iloc Accessors
- The second value inside the square brackets targets the columns.
- The `iloc` requires numeric positions for rows and columns.
- The `loc` requires labels for rows and columns.

In [30]:
bond = pd.read_csv("jamesbond.csv", index_col= "Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [42]:
bond.loc["Diamonds Are Forever","Director"]
bond.loc[["Octopussy","GoldenEye"],"Director"]
bond.loc[["Octopussy","GoldenEye"],"Director":"Budget"]
bond.loc["GoldenEye":"Octopussy","Director":"Budget"]
bond.loc["GoldenEye":"Octopussy",["Actor","Bond Actor Salary", "Year"]]

                                Actor  Bond Actor Salary  Year
Film
GoldenEye              Pierce Brosnan                5.1  1995
Goldfinger               Sean Connery                3.2  1964
Licence to Kill        Timothy Dalton                7.9  1989
Live and Let Die          Roger Moore                NaN  1973
Moonraker                 Roger Moore                NaN  1979
Never Say Never Again    Sean Connery                NaN  1983
No Time to Die           Daniel Craig               25.0  2021
Octopussy                 Roger Moore                7.8  1983

In [46]:
bond.iloc[0,2]

bond.iloc[3,5]

bond.iloc[[0,2],[3,5]]

bond.iloc[:2,:3]

                  Year        Actor    Director
Film
A View to a Kill  1985  Roger Moore   John Glen
Casino Royale     1967  David Niven  Ken Hughes

## Overwrite Value in a DataFrame
- Use the `iloc` or `loc` accessor on the **DataFrame** to target a value, then provide the equal sign and a new value.

In [47]:
bond = pd.read_csv("jamesbond.csv", index_col= "Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [50]:
bond.loc["Diamonds Are Forever","Actor"] = "Sir Sean Connery"

In [51]:
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Diamonds Are Forever,1971,Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

##  Overwrite Multiple Values in a DataFrame
- The `replace` method replaces all occurrences of a **Series** value with another value (think of it like "Find and Replace").
- To overwrite multiple values in a **DataFrame**, remember to use an accessor on the **DataFrame** itself.
- Accessors like `loc` and `iloc` can accept Boolean Series. Use them to target the values to overwrite.

In [56]:
bond = pd.read_csv("jamesbond.csv", index_col= "Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [54]:
bond["Actor"] = bond["Actor"].replace("Sean Connery", "Sir Sean Connery")

In [58]:
is_sean_connery = bond["Actor"] == "Sean Connery"
bond.loc[is_sean_connery, "Actor"] = "Sir Sean Connery"

## Rename Index Labels or Columns in a DataFrame
- The `rename` method accepts a dictionary for either its `columns` or `index` parameters.
- The dictionary keys represent the existing names and the values represent the new names.
- We can replace all columns by overwriting the **DataFrame's** `columns` attribute.

In [59]:
bond = pd.read_csv("jamesbond.csv", index_col= "Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [61]:
bond = bond.rename(columns = {"Year" : "Year of Release", "Box Office": "Revenue"})
bond.head()

,Year of Release,Actor,Director,Revenue,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [63]:
swaps = {
    "Dr. No": "Dr No",
    "GoldenEye": "Golden Eye",
    "The Word Is Not Enough" : "Best Bond Movie Ever"
}

bond.rename(index=swaps).head()

,Year of Release,Actor,Director,Revenue,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [65]:
bond.columns = ["Year", "Bond Guy", "Camera Dude", "Revenues", "Cost", "Salary"]

In [66]:
bond.columns

Index(['Year', 'Bond Guy', 'Camera Dude', 'Revenues', 'Cost', 'Salary'], dtype='str')

## Delete Rows or Columns from a DataFrame
- The `drop` method deletes one or more rows/columns from a **DataFrame**.
- Pass the `index` or `columns` parameters a list of the column names to remove.
- The `pop` method removes and returns a single **Series** (it mutates the **DataFrame** in the process).
- Python's `del` keyword also removes a single **Series**.

In [75]:
bond = pd.read_csv("jamesbond.csv", index_col= "Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [71]:
bond.drop(columns=["Box Office","Budget"]).head()
bond.drop(index=["Casino Royale","Die Another Day"]).head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6

In [76]:
bond.pop("Actor")

Film
A View to a Kill                      Roger Moore
Casino Royale                         David Niven
Casino Royale                        Daniel Craig
Diamonds Are Forever                 Sean Connery
Die Another Day                    Pierce Brosnan
Dr. No                               Sean Connery
For Your Eyes Only                    Roger Moore
From Russia with Love                Sean Connery
GoldenEye                          Pierce Brosnan
Goldfinger                           Sean Connery
Licence to Kill                    Timothy Dalton
Live and Let Die                      Roger Moore
Moonraker                             Roger Moore
Never Say Never Again                Sean Connery
No Time to Die                       Daniel Craig
Octopussy                             Roger Moore
On Her Majesty's Secret Service    George Lazenby
Quantum of Solace                    Daniel Craig
Skyfall                              Daniel Craig
Spectre                              Daniel Craig
The Living Daylights               Timothy Dalton
The Man with the Golden Gun           Roger Moore
The Spy Who Loved Me                  Roger Moore
The World Is Not Enough            Pierce Brosnan
Thunderball                          Sean Connery
Tomorrow Never Dies                Pierce Brosnan
You Only Live Twice                  Sean Connery
Name: Actor, dtype: str

In [77]:
bond.head()

,Year,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,
A View to a Kill,1985,John Glen,275.2,54.5,9.1
Casino Royale,1967,Ken Hughes,315.0,85.0,NaN
Casino Royale,2006,Martin Campbell,581.5,145.3,3.3
Diamonds Are Forever,1971,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Lee Tamahori,465.4,154.2,17.9

## Create Random Sample with the sample Method
- The `sample` method returns a specified one or more random rows from the **DataFrame**.
- Customize the `axis` parameter to extract random columns.

In [78]:
bond = pd.read_csv("jamesbond.csv", index_col= "Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [83]:
bond.sample()
bond.sample(n=5)
bond.sample(n=3, axis="rows")
bond.sample(n=3, axis="columns").head()

                      Year  Bond Actor Salary  Box Office
Film
A View to a Kill      1985                9.1       275.2
Casino Royale         1967                NaN       315.0
Casino Royale         2006                3.3       581.5
Diamonds Are Forever  1971                5.8       442.5
Die Another Day       2002               17.9       465.4

## The nsmallest and nlargest Methods
- The `nlargest` method returns a specified number of rows with the largest values from a given column.
- The `nsmallest` method returns rows with the smallest values from a given column.
- The `nlargest` and `nsmallest` methods are more efficient than sorting the entire **DataFrame**.

In [84]:
bond = pd.read_csv("jamesbond.csv", index_col= "Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [85]:
# Retrieve the 4 films with the highest/largest Box Office gross
bond.sort_values("Box Office", ascending = False). head(4)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [88]:
bond.nlargest(4, columns = "Box Office")
bond["Box Office"].nlargest(4)

Film
Skyfall           943.5
Thunderball       848.1
Goldfinger        820.4
No Time to Die    774.2
Name: Box Office, dtype: float64

In [91]:
bond.nsmallest(3, columns = "Bond Actor Salary")
bond["Bond Actor Salary"].nsmallest(3)

Film
Dr. No                             0.6
On Her Majesty's Secret Service    0.6
From Russia with Love              1.6
Name: Bond Actor Salary, dtype: float64

## Filtering with the where Method
- Similar to square brackets or `loc`, the `where` method filters the original `DataFrame` with a Boolean Series.
- Pandas will populate rows that do **not** match the criteria with `NaN` values.
- Leaving in the `NaN` values can be advantageous for certain merge and visualization operations.

In [95]:
bond = pd.read_csv("jamesbond.csv", index_col= "Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [ ]:
actor_is_sean_connery = bond["Actor"] == "Sean Connery"
bond[actor_is_sean_connery]
bond.loc[actor_is_sean_connery]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [109]:
bond.loc[bond["Actor"] == "Sean Connery", :]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [111]:
bond.where(actor_is_sean_connery).head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Diamonds Are Forever,1971.0,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,NaN,NaN,NaN,NaN,NaN,NaN

## The apply Method with DataFrames
- The `apply` method invokes a function on every column or every row in the **DataFrame**.
- Pass the uninvoked function as the first argument to the `apply` method.
- Pass the `axis` parameter an argument of `"columns"` to invoke the function on every row.
- Pandas will pass in the row's values as a **Series** object. We can use accessors like `loc` and `iloc` to extract the column's values for that row.

In [112]:
bond = pd.read_csv("jamesbond.csv", index_col= "Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [113]:
bond["Actor"].apply(len)

Film
A View to a Kill                   11
Casino Royale                      11
Casino Royale                      12
Diamonds Are Forever               12
Die Another Day                    14
Dr. No                             12
For Your Eyes Only                 11
From Russia with Love              12
GoldenEye                          14
Goldfinger                         12
Licence to Kill                    14
Live and Let Die                   11
Moonraker                          11
Never Say Never Again              12
No Time to Die                     12
Octopussy                          11
On Her Majesty's Secret Service    14
Quantum of Solace                  12
Skyfall                            12
Spectre                            12
The Living Daylights               14
The Man with the Golden Gun        11
The Spy Who Loved Me               11
The World Is Not Enough            14
Thunderball                        12
Tomorrow Never Dies                14
You Only Live Twice                12
Name: Actor, dtype: int64

In [114]:
bond.head(1)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1

In [ ]:
# Movie Ranking System
#
# CONDITION -) DESIGNATON
# 80s movie -) "Great 80's flick"
# Pierce Brosnan -) "The best Bond ever"
# Budget > 100 -) "Expensive movie, fun"
# Others -) "No comment"Any
def rank_movie(row):
    year = row.loc["Year"]
    actor = row.loc["Actor"]
    budget = row.loc["Budget"]

    if year >= 1980 and year < 1990:
        return "Great 80's flick!"
    
    if actor == "Pierce Brosnan":
        return "The best Bond ever!"
    
    if budget >100:
        return "Expensive movie, fun"
    
    return "No comment"

bond.apply(rank_movie, axis = "columns")

Year                        1985
Actor                Roger Moore
Director               John Glen
Box Office                 275.2
Budget                      54.5
Bond Actor Salary            9.1
Name: A View to a Kill, dtype: object
Year                        1967
Actor                David Niven
Director              Ken Hughes
Box Office                 315.0
Budget                      85.0
Bond Actor Salary            NaN
Name: Casino Royale, dtype: object
Year                            2006
Actor                   Daniel Craig
Director             Martin Campbell
Box Office                     581.5
Budget                         145.3
Bond Actor Salary                3.3
Name: Casino Royale, dtype: object
Year                         1971
Actor                Sean Connery
Director             Guy Hamilton
Box Office                  442.5
Budget                       34.7
Bond Actor Salary             5.8
Name: Diamonds Are Forever, dtype: object
Year                           2002
Actor                Pierce Brosnan
Director               Lee Tamahori
Box Office                    465.4
Budget                        154.2
Bond Actor Salary              17.9
Name: Die Another Day, dtype: object
Year                          1962
Actor                 Sean Connery
Director             Terence Young
Box Office                   448.8
Budget                         7.0
Bond Actor Salary              0.6
Name: Dr. No, dtype: object
Year                        1981
Actor                Roger Moore
Director               John Glen
Box Office                 449.4
Budget                      60.2
Bond Actor Salary            NaN
Name: For Your Eyes Only, dtype: object
Year                          1963
Actor                 Sean Connery
Director             Terence Young
Box Office                   543.8
Budget                        12.6
Bond Actor Salary              1.6
Name: From Russia with Love, dtype: object
Year                            1995
Actor                 Pierce Brosnan
Director             Martin Campbell
Box Office                     518.5
Budget                          76.9
Bond Actor Salary                5.1
Name: GoldenEye, dtype: object
Year                         1964
Actor                Sean Connery
Director             Guy Hamilton
Box Office                  820.4
Budget                       18.6
Bond Actor Salary             3.2
Name: Goldfinger, dtype: object
Year                           1989
Actor                Timothy Dalton
Director                  John Glen
Box Office                    250.9
Budget                         56.7
Bond Actor Salary               7.9
Name: Licence to Kill, dtype: object
Year                         1973
Actor                 Roger Moore
Director             Guy Hamilton
Box Office                  460.3
Budget                       30.8
Bond Actor Salary             NaN
Name: Live and Let Die, dtype: object
Year                          1979
Actor                  Roger Moore
Director             Lewis Gilbert
Box Office                   535.0
Budget                        91.5
Bond Actor Salary              NaN
Name: Moonraker, dtype: object
Year                           1983
Actor                  Sean Connery
Director             Irvin Kershner
Box Office                    380.0
Budget                         86.0
Bond Actor Salary               NaN
Name: Never Say Never Again, dtype: object
Year                               2021
Actor                      Daniel Craig
Director             Cary Joji Fukunaga
Box Office                        774.2
Budget                            301.0
Bond Actor Salary                  25.0
Name: No Time to Die, dtype: object
Year                        1983
Actor                Roger Moore
Director               John Glen
Box Office                 373.8
Budget                      53.9
Bond Actor Salary            7.8
Name: Octopussy, dtype: object
Year                           1969
Actor                George Lazenby
Director              Peter R. Hunt
Box Office                    291.5
Budget                         37.3
Bond Actor Salary               0.6
Name: On Her Majesty's Secret Service, dtype: object
Year                         2008
Actor                Daniel Craig
Director             Marc Forster
Box Office                  514.2
Budget                      181.4
Bond Actor Salary             8.1
Name: Quantum of Solace, dtype: object
Year                         2012
Actor                Daniel Craig
Director               Sam Mendes
Box Office                  943.5
Budget                      170.2
Bond Actor Salary            14.5
Name: Skyfall, dtype: object
Year                         2015
Actor                Daniel Craig
Director               Sam Mendes
Box Office                  726.7
Budget                      206.3
Bond Actor Salary            30.0
Name: Spectre, dtype: object
Year                           1987
Actor                Timothy Dalton
Director                  John Glen
Box Office                    313.5
Budget                         68.8
Bond Actor Salary               5.2
Name: The Living Daylights, dtype: object
Year                         1974
Actor                 Roger Moore
Director             Guy Hamilton
Box Office                  334.0
Budget                       27.7
Bond Actor Salary             NaN
Name: The Man with the Golden Gun, dtype: object
Year                          1977
Actor                  Roger Moore
Director             Lewis Gilbert
Box Office                   533.0
Budget                        45.1
Bond Actor Salary              NaN
Name: The Spy Who Loved Me, dtype: object
Year                           1999
Actor                Pierce Brosnan
Director              Michael Apted
Box Office                    439.5
Budget                        158.3
Bond Actor Salary              13.5
Name: The World Is Not Enough, dtype: object
Year                          1965
Actor                 Sean Connery
Director             Terence Young
Box Office                   848.1
Budget                        41.9
Bond Actor Salary              4.7
Name: Thunderball, dtype: object
Year                               1997
Actor                    Pierce Brosnan
Director             Roger Spottiswoode
Box Office                        463.2
Budget                            133.9
Bond Actor Salary                  10.0
Name: Tomorrow Never Dies, dtype: object
Year                          1967
Actor                 Sean Connery
Director             Lewis Gilbert
Box Office                   514.2
Budget                        59.9
Bond Actor Salary              4.4
Name: You Only Live Twice, dtype: object

Film
A View to a Kill                   None
Casino Royale                      None
Casino Royale                      None
Diamonds Are Forever               None
Die Another Day                    None
Dr. No                             None
For Your Eyes Only                 None
From Russia with Love              None
GoldenEye                          None
Goldfinger                         None
Licence to Kill                    None
Live and Let Die                   None
Moonraker                          None
Never Say Never Again              None
No Time to Die                     None
Octopussy                          None
On Her Majesty's Secret Service    None
Quantum of Solace                  None
Skyfall                            None
Spectre                            None
The Living Daylights               None
The Man with the Golden Gun        None
The Spy Who Loved Me               None
The World Is Not Enough            None
Thunderball                        None
Tomorrow Never Dies                None
You Only Live Twice                None
dtype: object