# MultiIndex

In [1]:
import pandas as pd

## This Module's Dataset

In [5]:
bigmac = pd.read_csv("bigmac.csv", parse_dates=["Date"], date_format="%Y-%m-%d")
bigmac.head()

        Date      Country  Price in US Dollars
0 2000-04-01    Argentina             2.500000
1 2000-04-01    Australia             1.541667
2 2000-04-01       Brazil             1.648045
3 2000-04-01       Canada             1.938776
4 2000-04-01  Switzerland             3.470588

In [6]:
bigmac.dtypes

Date                   datetime64[us]
Country                           str
Price in US Dollars           float64
dtype: object

In [7]:
bigmac.info()

<class 'pandas.DataFrame'>
RangeIndex: 1386 entries, 0 to 1385
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 1386 non-null   datetime64[us]
 1   Country              1386 non-null   str
 2   Price in US Dollars  1386 non-null   float64
dtypes: datetime64[us](1), float64(1), str(1)
memory usage: 43.2 KB

## Create a MultiIndex
- A **MultiIndex** is an index with multiple levels or layers.
- Pass the `set_index` method a list of colum names to create a multi-index **DataFrame**.
- The order of the list's values will determine the order of the levels.
- Alternatively, we can pass the `read_csv` function's `index_col` parameter a list of columns.

In [13]:
bigmac = pd.read_csv("bigmac.csv", parse_dates=["Date"], date_format="%Y-%m-%d", index_col=["Date","Country"])
bigmac.head()

                        Price in US Dollars
Date       Country
2000-04-01 Argentina               2.500000
           Australia               1.541667
           Brazil                  1.648045
           Canada                  1.938776
           Switzerland             3.470588

In [12]:
bigmac = bigmac.set_index(keys=["Date","Country"])

In [11]:
bigmac.nunique()

Date                     33
Country                  57
Price in US Dollars    1350
dtype: int64

In [14]:
bigmac.index.names

FrozenList(['Date', 'Country'])

## Extract Index Level Values
- The `get_level_values` method extracts an **Index** with the values from one level in the **MultiIndex**.
- Invoke the `get_level_values` on the **MultiIndex**, not the **DataFrame** itself.
- The method expects either the level's index position or its name.

In [15]:
bigmac = pd.read_csv("bigmac.csv", parse_dates=["Date"], date_format="%Y-%m-%d", index_col=["Date","Country"])
bigmac.head()

                        Price in US Dollars
Date       Country
2000-04-01 Argentina               2.500000
           Australia               1.541667
           Brazil                  1.648045
           Canada                  1.938776
           Switzerland             3.470588

In [20]:
bigmac.index.get_level_values("Date")
bigmac.index.get_level_values(0)

bigmac.index.get_level_values("Country")
bigmac.index.get_level_values(1)

Index(['Argentina', 'Australia', 'Brazil', 'Canada', 'Switzerland', 'Chile',
       'China', 'Czech Republic', 'Denmark', 'Euro area',
       ...
       'Singapore', 'Sweden', 'Thailand', 'Turkey', 'Taiwan', 'Ukraine',
       'Uruguay', 'United States', 'Vietnam', 'South Africa'],
      dtype='str', name='Country', length=1386)

## Rename Index Levels
- Invoke the `set_names` method on the **MultiIndex** to change one or more level names.
- Use the `names` and `level` parameter to target a nested index at a given level.
- Alternatively, pass `names` a list of strings to overwrite *all* level names.
- The `set_names` method returns a copy, so replace the original index to alter the **DataFrame**.

In [21]:
bigmac = pd.read_csv("bigmac.csv", parse_dates=["Date"], date_format="%Y-%m-%d", index_col=["Date","Country"])
bigmac.head()

                        Price in US Dollars
Date       Country
2000-04-01 Argentina               2.500000
           Australia               1.541667
           Brazil                  1.648045
           Canada                  1.938776
           Switzerland             3.470588

In [26]:
bigmac.index.set_names(names="Time",level=0)
bigmac.index.set_names(names="Country",level=1)
bigmac.index.set_names(names = ["Country","Location"])

MultiIndex([('2000-04-01',      'Argentina'),
            ('2000-04-01',      'Australia'),
            ('2000-04-01',         'Brazil'),
            ('2000-04-01',         'Canada'),
            ('2000-04-01',    'Switzerland'),
            ('2000-04-01',          'Chile'),
            ('2000-04-01',          'China'),
            ('2000-04-01', 'Czech Republic'),
            ('2000-04-01',        'Denmark'),
            ('2000-04-01',      'Euro area'),
            ...
            ('2020-07-01',      'Singapore'),
            ('2020-07-01',         'Sweden'),
            ('2020-07-01',       'Thailand'),
            ('2020-07-01',         'Turkey'),
            ('2020-07-01',         'Taiwan'),
            ('2020-07-01',        'Ukraine'),
            ('2020-07-01',        'Uruguay'),
            ('2020-07-01',  'United States'),
            ('2020-07-01',        'Vietnam'),
            ('2020-07-01',   'South Africa')],
           names=['Country', 'Location'], length=1386)

## The sort_index Method on a MultiIndex DataFrame
- Using the `sort_index` method, we can target all levels or specific levels of the **MultiIndex**.
- To apply a different sort order to different levels, pass a list of Booleans.

In [27]:
bigmac = pd.read_csv("bigmac.csv", parse_dates=["Date"], date_format="%Y-%m-%d", index_col=["Date","Country"])
bigmac.head()

                        Price in US Dollars
Date       Country
2000-04-01 Argentina               2.500000
           Australia               1.541667
           Brazil                  1.648045
           Canada                  1.938776
           Switzerland             3.470588

In [28]:
bigmac.sort_index()

                                 Price in US Dollars
Date       Country
2000-04-01 Argentina                        2.500000
           Australia                        1.541667
           Brazil                           1.648045
           Britain                          3.002000
           Canada                           1.938776
...                                              ...
2020-07-01 Ukraine                          2.174714
           United Arab Emirates             4.015846
           United States                    5.710000
           Uruguay                          4.327418
           Vietnam                          2.847282

[1386 rows x 1 columns]

In [30]:
bigmac.sort_index(ascending=True)
bigmac.sort_index(ascending=False)

                                 Price in US Dollars
Date       Country
2020-07-01 Vietnam                          2.847282
           Uruguay                          4.327418
           United States                    5.710000
           United Arab Emirates             4.015846
           Ukraine                          2.174714
...                                              ...
2000-04-01 Canada                           1.938776
           Britain                          3.002000
           Brazil                           1.648045
           Australia                        1.541667
           Argentina                        2.500000

[1386 rows x 1 columns]

In [31]:
bigmac.sort_index(ascending=[False,True])

                          Price in US Dollars
Date       Country
2020-07-01 Argentina                 3.509232
           Australia                 4.578450
           Azerbaijan                2.324897
           Bahrain                   3.713035
           Brazil                    3.913528
...                                       ...
2000-04-01 Sweden                    2.714932
           Switzerland               3.470588
           Taiwan                    2.287582
           Thailand                  1.447368
           United States             2.510000

[1386 rows x 1 columns]

## Extract Rows from a MultiIndex DataFrame
- A **tuple** is an immutable list. It cannot be modified after creation.
- Create a tuple with a comma between elements. The community convention is to wrap the elements in parentheses.
- The `iloc` and `loc` accessors are available to extract rows by index position or label.
- For the `loc` accessor, pass a tuple to hold the labels from the index levels.

In [32]:
bigmac = pd.read_csv("bigmac.csv", parse_dates=["Date"], date_format="%Y-%m-%d", index_col=["Date","Country"]).sort_index()
bigmac.head()

                      Price in US Dollars
Date       Country
2000-04-01 Argentina             2.500000
           Australia             1.541667
           Brazil                1.648045
           Britain               3.002000
           Canada                1.938776

In [33]:
bigmac.iloc[2]

Price in US Dollars    1.648045
Name: (2000-04-01 00:00:00, Brazil), dtype: float64

In [35]:
bigmac.loc["2000-04-01"].head()

           Price in US Dollars
Country
Argentina             2.500000
Australia             1.541667
Brazil                1.648045
Britain               3.002000
Canada                1.938776

In [36]:
bigmac.loc["2000-04-01","Canada"]

Price in US Dollars    1.938776
Name: (2000-04-01 00:00:00, Canada), dtype: float64

In [38]:
bigmac.loc["2000-04-01","Price in US Dollars"].head()

Country
Argentina    2.500000
Australia    1.541667
Brazil       1.648045
Britain      3.002000
Canada       1.938776
Name: Price in US Dollars, dtype: float64

In [40]:
bigmac.loc[("2000-04-01","Canada")]

Price in US Dollars    1.938776
Name: (2000-04-01 00:00:00, Canada), dtype: float64

In [42]:
bigmac.loc[("2000-04-01","Hungary"):("2000-04-01","Poland")]

                        Price in US Dollars
Date       Country
2000-04-01 Hungary                 1.215054
           Indonesia               1.825047
           Israel                  3.580247
           Japan                   2.773585
           Malaysia                1.189474
           Mexico                  2.221041
           New Zealand             1.691542
           Poland                  1.279070

In [44]:
start = ("2000-04-01","Hungary")
end = ("2000-04-01","Poland")
bigmac.loc[start:end]

                        Price in US Dollars
Date       Country
2000-04-01 Hungary                 1.215054
           Indonesia               1.825047
           Israel                  3.580247
           Japan                   2.773585
           Malaysia                1.189474
           Mexico                  2.221041
           New Zealand             1.691542
           Poland                  1.279070

## The transpose Method
- The `transpose` method inverts/flips the horizontal and vertical axes of the **DataFrame**.

In [47]:
bigmac = pd.read_csv("bigmac.csv", parse_dates=["Date"], date_format="%Y-%m-%d", index_col=["Date","Country"]).sort_index()
bigmac.head()

                      Price in US Dollars
Date       Country
2000-04-01 Argentina             2.500000
           Australia             1.541667
           Brazil                1.648045
           Britain               3.002000
           Canada                1.938776

In [49]:
start = ("2018-01-01","China")
end = ("2018-01-01","Denmark")

bigmac.loc[start:end].transpose()

Date                2018-01-01
Country                  China  Colombia Costa Rica Czech Republic  Denmark
Price in US Dollars   3.171642  3.832468   4.027932       3.807779  4.93202

## The stack Method
- The `stack` method moves the column index to the row index.
- Pandas will return a **MultiIndex Series**.
- Think of it like "stacking" index levels for a **MultiIndex**.

In [55]:
world = pd.read_csv("worldstats.csv", index_col=["year","country"]).sort_index()
world

                           Population           GDP
year country
1960 Afghanistan         8.994793e+06  5.377778e+08
     Algeria             1.112489e+07  2.723638e+09
     Australia           1.027648e+07  1.856759e+10
     Austria             7.047539e+06  6.592694e+09
     Bahamas, The        1.095260e+05  1.698023e+08
...                               ...           ...
2015 Vietnam             9.170380e+07  1.935994e+11
     West Bank and Gaza  4.422143e+06  1.267740e+10
     World               7.346633e+09  7.343364e+13
     Zambia              1.621177e+07  2.120156e+10
     Zimbabwe            1.560275e+07  1.389294e+10

[11211 rows x 2 columns]

In [56]:
world.stack()

year  country
1960  Afghanistan  Population    8.994793e+06
                   GDP           5.377778e+08
      Algeria      Population    1.112489e+07
                   GDP           2.723638e+09
      Australia    Population    1.027648e+07
                                     ...
2015  World        GDP           7.343364e+13
      Zambia       Population    1.621177e+07
                   GDP           2.120156e+10
      Zimbabwe     Population    1.560275e+07
                   GDP           1.389294e+10
Length: 22422, dtype: float64

In [57]:
world.stack().to_frame()

                                        0
year country
1960 Afghanistan Population  8.994793e+06
                 GDP         5.377778e+08
     Algeria     Population  1.112489e+07
                 GDP         2.723638e+09
     Australia   Population  1.027648e+07
...                                   ...
2015 World       GDP         7.343364e+13
     Zambia      Population  1.621177e+07
                 GDP         2.120156e+10
     Zimbabwe    Population  1.560275e+07
                 GDP         1.389294e+10

[22422 rows x 1 columns]

## The unstack Method
- The `unstack` method moves a row index to the column index (the inverse of the `stack` method).
- By default, the `unstack` method will move the innermost index.
- We can customize the moved index with the `level` parameter.
- The `level` parameter accepts the level's index position or its name. It can also accept a list of positions/names.

In [59]:
world = pd.read_csv("worldstats.csv", index_col=["year","country"]).sort_index().stack()
world

year  country
1960  Afghanistan  Population    8.994793e+06
                   GDP           5.377778e+08
      Algeria      Population    1.112489e+07
                   GDP           2.723638e+09
      Australia    Population    1.027648e+07
                                     ...
2015  World        GDP           7.343364e+13
      Zambia       Population    1.621177e+07
                   GDP           2.120156e+10
      Zimbabwe     Population    1.560275e+07
                   GDP           1.389294e+10
Length: 22422, dtype: float64

In [61]:
world.unstack().columns

Index(['Population', 'GDP'], dtype='str')

In [62]:
world.unstack().unstack().columns

MultiIndex([('Population',           'Afghanistan'),
            ('Population',               'Albania'),
            ('Population',               'Algeria'),
            ('Population',               'Andorra'),
            ('Population',                'Angola'),
            ('Population',   'Antigua and Barbuda'),
            ('Population',            'Arab World'),
            ('Population',             'Argentina'),
            ('Population',               'Armenia'),
            ('Population',                 'Aruba'),
            ...
            (       'GDP',            'Uzbekistan'),
            (       'GDP',               'Vanuatu'),
            (       'GDP',         'Venezuela, RB'),
            (       'GDP',               'Vietnam'),
            (       'GDP', 'Virgin Islands (U.S.)'),
            (       'GDP',    'West Bank and Gaza'),
            (       'GDP',                 'World'),
            (       'GDP',           'Yemen, Rep.'),
            (       'GDP',                'Zambia'),
            (       'GDP',              'Zimbabwe')],
           names=[None, 'country'], length=504)

## The pivot Method
- The `pivot` method reshapes data from a tall format to a wide format.
- Ask yourself which direction the data will expand in if you add more entries.
- A tall/long format expands down. A wide format expands out.
- The `index` parameter sets the horizontal index of the pivoted **DataFrame**.
- The `columns` parameter sets the column whose values will be the columns in the pivoted **DataFrame**.
- The `values` parameter set the values of the pivoted **DataFrame**. Pandas will populate the correct values based on the index and column intersections.

In [70]:
sales = pd.read_csv("salesmen.csv")
sales

            Date Salesman  Revenue
0       1/1/2025   Sharon     7172
1       1/2/2025   Sharon     6362
2       1/3/2025   Sharon     5982
3       1/4/2025   Sharon     7917
4       1/5/2025   Sharon     7837
...          ...      ...      ...
1820  12/27/2025    Oscar      835
1821  12/28/2025    Oscar     3073
1822  12/29/2025    Oscar     6424
1823  12/30/2025    Oscar     7088
1824  12/31/2025    Oscar     8408

[1825 rows x 3 columns]

In [72]:
sales.pivot(index="Date", columns="Salesman", values="Revenue").sort_index()

Salesman   Alexander  Dave  Oscar  Ronald  Sharon
Date
1/1/2025        4430  1864   5250    2639    7172
1/10/2025        301  7105   7663    8267    7543
1/11/2025       9489  6851   8888    1340    1053
1/12/2025       8719  7147   3092     279    4362
1/13/2025       2349  6160   6139    7540    6812
...              ...   ...    ...     ...     ...
9/5/2025        2439   211   7743    4252     992
9/6/2025        7585  7293   5072    1112     556
9/7/2025        6669  9774   5230    3608    6499
9/8/2025        3058  8194   7755    5762    9621
9/9/2025        6823  4733   5684    8922    1231

[365 rows x 5 columns]

## The melt Method
- The `melt` method is the inverse of the `pivot` method.
- It takes a 'wide' dataset and converts it to a 'tall' dataset.
- The `melt` method is ideal when you have multiple columns storing the *same* data point.
- Ask yourself whether the column's values are a *type* of the column header. If they're not, the data is likely stored in a wide format.
- The `id_vars` parameters accepts the column whose values will be repeated for every column.
- The `var_name` parameter sets the name of the new column for the varying values (the former column names).
- The `value_name` parameter set the new name of the values column (holding the values from the original **DataFrame**).

In [74]:
quaters = pd.read_csv("quarters.csv")
quaters

    Salesman      Q1      Q2      Q3      Q4
0      Boris  602908  233879  354479   32704
1      Piers   43790  514863  297151  544493
2      Tommy  392668  113579  430882  247231
3     Travis  834663  266785  749238  570524
4      Cindy  580935  411379  110390  651572
5        Rob  656644   70803  375948  321388
6       Mike  486141  600753  742716  404995
7      Stacy  479662  742806  770712    2501
8  Alexandra  992673  879183   37945  293710

In [77]:
quaters.melt(id_vars="Salesman",var_name="Quarter",value_name="Revenue")

     Salesman Quarter  Revenue
0       Boris      Q1   602908
1       Piers      Q1    43790
2       Tommy      Q1   392668
3      Travis      Q1   834663
4       Cindy      Q1   580935
5         Rob      Q1   656644
6        Mike      Q1   486141
7       Stacy      Q1   479662
8   Alexandra      Q1   992673
9       Boris      Q2   233879
10      Piers      Q2   514863
11      Tommy      Q2   113579
12     Travis      Q2   266785
13      Cindy      Q2   411379
14        Rob      Q2    70803
15       Mike      Q2   600753
16      Stacy      Q2   742806
17  Alexandra      Q2   879183
18      Boris      Q3   354479
19      Piers      Q3   297151
20      Tommy      Q3   430882
21     Travis      Q3   749238
22      Cindy      Q3   110390
23        Rob      Q3   375948
24       Mike      Q3   742716
25      Stacy      Q3   770712
26  Alexandra      Q3    37945
27      Boris      Q4    32704
28      Piers      Q4   544493
29      Tommy      Q4   247231
30     Travis      Q4   570524
31      Cindy      Q4   651572
32        Rob      Q4   321388
33       Mike      Q4   404995
34      Stacy      Q4     2501
35  Alexandra      Q4   293710

## The pivot_table Method
- The `pivot_table` method operates similarly to the Pivot Table feature in Excel.
- A pivot table is a table whose values are aggregations of groups of values from another table.
- The `values` parameter accepts the numeric column whose values will be aggregated.
- The `aggfunc` parameter declares the aggregation function (the default is mean/average).
- The `index` parameter sets the index labels of the pivot table. MultiIndexes are permitted.
- The `columns` parameter sets the column labels of the pivot table. MultiIndexes are permitted.

In [79]:
foods = pd.read_csv("foods.csv")
foods.head()

  First Name  Gender          City Frequency       Item  Spend
0      Wanda  Female      Stamford    Weekly     Burger  15.66
1       Eric    Male      Stamford     Daily    Chalupa  10.56
2    Charles    Male      New York     Never      Sushi  42.14
3       Anna  Female  Philadelphia      Once  Ice Cream  11.01
4    Deborah  Female  Philadelphia     Daily    Chalupa  23.49

In [83]:
foods.pivot_table(values="Spend",index="Gender")
foods.pivot_table(values="Spend",index="Gender", aggfunc="mean")
foods.pivot_table(values="Spend",index="Gender", aggfunc="sum")

           Spend
Gender
Female  25963.33
Male    24106.04

In [84]:
foods.pivot_table(values="Spend",index="Item", aggfunc="sum")

             Spend
Item
Burger     7765.73
Burrito    8270.44
Chalupa    7644.52
Donut      8758.76
Ice Cream  8886.99
Sushi      8742.93

In [85]:
foods.pivot_table(values="Spend",index=["Gender","Item"], aggfunc="sum")

                    Spend
Gender Item
Female Burger     4094.30
       Burrito    4257.82
       Chalupa    4152.26
       Donut      4743.00
       Ice Cream  4032.87
       Sushi      4683.08
Male   Burger     3671.43
       Burrito    4012.62
       Chalupa    3492.26
       Donut      4015.76
       Ice Cream  4854.12
       Sushi      4059.85

In [86]:
foods.pivot_table(values="Spend",index=["Gender","Item"],columns="City", aggfunc="sum")

City              New York  Philadelphia  Stamford
Gender Item
Female Burger      1239.04       1639.24   1216.02
       Burrito      978.95       1458.76   1820.11
       Chalupa      876.58       1673.33   1602.35
       Donut       1446.78       1639.26   1656.96
       Ice Cream   1521.62       1479.22   1032.03
       Sushi       1480.29       1742.88   1459.91
Male   Burger      1294.09        938.18   1439.16
       Burrito     1399.40       1312.93   1300.29
       Chalupa     1227.77       1114.23   1150.26
       Donut       1345.27       1249.36   1421.13
       Ice Cream   1603.63       2191.27   1059.22
       Sushi       1396.15       1395.88   1267.82

In [90]:
foods.pivot_table(values="Spend",index="Item",columns=["Gender","City"], aggfunc="mean")

Gender        Female                               Male               \
City        New York Philadelphia   Stamford   New York Philadelphia
Item
Burger     51.626667    52.878710  45.037778  58.822273    44.675238
Burrito    42.563043    52.098571  53.532647  55.976000    43.764333
Chalupa    46.135789    52.291562  64.094000  49.110800    48.444783
Donut      46.670323    54.642000  48.734118  44.842333    37.859394
Ice Cream  56.356296    46.225625  46.910455  55.297586    53.445610
Sushi      47.751290    58.096000  45.622188  51.709259    49.852857

Gender
City        Stamford
Item
Burger     46.424516
Burrito    46.438929
Chalupa    50.011304
Donut      49.004483
Ice Cream  42.368800
Sushi      70.434444

In [91]:
foods.pivot_table(values="Spend",index="Item",columns=["Gender","City"], aggfunc="count")

Gender      Female                           Male
City      New York Philadelphia Stamford New York Philadelphia Stamford
Item
Burger          24           31       27       22           21       31
Burrito         23           28       34       25           30       28
Chalupa         19           32       25       25           23       23
Donut           31           30       34       30           33       29
Ice Cream       27           32       22       29           41       25
Sushi           31           30       32       27           28       18

In [92]:
foods.pivot_table(values="Spend",index="Item",columns=["Gender","City"], aggfunc="max")

Gender      Female                           Male
City      New York Philadelphia Stamford New York Philadelphia Stamford
Item
Burger       98.96        97.79    85.06    90.32        99.68    97.20
Burrito      92.25        96.79    99.21    98.04        93.27    95.07
Chalupa      98.43        99.29    98.78    96.44        98.40    99.87
Donut        95.63        96.52    91.75    86.70        93.12    99.26
Ice Cream    97.83        88.14    97.44    97.65        99.24    99.17
Sushi        99.51        99.02    95.43    93.85        97.12    98.48