In [1]:
import pandas as pd
import numpy as np
import json

In [2]:
df = pd.read_excel("MentorMe-CV-File-20260224.xlsx")
df.head()

,id,user_id,analysis_id,candidate_name,email,phone,status,file_name,created_at,updated_at,...,formatting_issues,sections.coreCompetencies,sections.leadershipManagement,sections.certifications,sections.languages,sections.passportVisaHistory,sections.military,sections.volunteer,sections.communityWork,additional_sections
0,2,NaN,1759998111377,Christopher Davis,chris.davis.1990@email.com,(415) 555-0776,craft,Christopher Davis_Flutter Developer.pdf,2025-10-09T08:22:24,2025-10-09T08:22:24,...,"[""Placeholder GitHub link text"",""LinkedIn URL ...",[],NaN,[],[],NaN,NaN,NaN,NaN,NaN
1,3,NaN,1759998769335,Minh Vu,vddminh89@gmail.com,(84) 090-4562633,craft,CV_Minh Vu - Minh Vu.pdf,2025-10-09T08:33:36,2025-10-09T08:33:36,...,"[""Hyphen and bullet mix inconsistent"",""No unif...","[""Problem solving"",""Leadership"",""ERP System Ev...",NaN,[],[],NaN,NaN,NaN,NaN,NaN
2,5,NaN,1759999340602,TRAN QUOC BAO,21bao.tq@vinuni.edu.vn,(+84) 382780002,craft,BaoTran_resume - BaÌo TraÌÌn.pdf,2025-10-09T08:42:56,2025-10-09T08:42:56,...,"[""Inconsistent date formats across entries"",""J...","[""Python"",""Matlab"",""TensorFlow"",""React.js"",""Fi...",NaN,"[""Deep Learning Specialization, DeepLearning.A...","[{""language"":""English"",""proficiency"":""Fluent""}]",NaN,NaN,NaN,NaN,NaN
3,11,NaN,1760001071242,Le Anh Vy (Chloe),chloe@theseedsoft.com,0404 262 401,craft,Le Anh Vy - CV.PDF,2025-10-09T09:12:00,2025-10-09T09:12:00,...,"[""Bullet styles vary"",""Overseas roles merged b...",[],NaN,"[""LinkedIN Project Management Certification""]",[],NaN,NaN,NaN,NaN,NaN
4,14,NaN,1760001127938,Le Anh Vy (Chloe),chloe@theseedsoft.com,0404 262 401,craft,Le Anh Vy - CV.PDF,2025-10-09T09:13:11,2025-10-09T09:13:11,...,"[""Inconsistent date format styles"",""Bullet sty...","[""Program Management"",""Project Management"",""Co...",NaN,"[""LinkedIN Project Management Certification | ...",[],NaN,NaN,NaN,NaN,NaN

### 1. Explore dataset first

#### Step 1 — Load & get the big picture

In [3]:
# (rows, columns) — how big is this?
# what are the column names?
# what data type did pandas guess for each column?
# first 5 rows — eyeball the data
# last 5 rows — any weird trailing rows?
# random 5 rows — avoids being fooled by "clean" top rows

In [4]:
# (rows, columns) — how big is this?
print("(rows, columns) — how big is this?")
print(df.shape)
print("\n")

# what data type did pandas guess for each column?
print(" what data type did pandas guess for each column?")
print(df.info())
print("\n")

# first 5 rows — eyeball the data
print(" first 5 rows — eyeball the data")
df.head(5).T

(rows, columns) — how big is this?
(189, 34)


 what data type did pandas guess for each column?
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189 entries, 0 to 188
Data columns (total 34 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id                             189 non-null    int64
 1   user_id                        63 non-null     float64
 2   analysis_id                    189 non-null    int64
 3   candidate_name                 180 non-null    object
 4   email                          172 non-null    object
 5   phone                          169 non-null    object
 6   status                         189 non-null    object
 7   file_name                      189 non-null    object
 8   created_at                     189 non-null    object
 9   updated_at                     189 non-null    object
 10  overview                       183 non-null    object
 11  technical_skills               189 non-null    object
 12  soft_skills                    189 non-null    object
 13  strengths                      189 non-null    object
 14  gaps                           189 non-null    object
 15  keywords                       189 non-null    object
 16  experience_level.level         184 non-null    object
 17  experience_level.years         189 non-null    int64
 18  recommendations                189 non-null    object
 19  regional_insights              189 non-null    object
 20  location                       156 non-null    object
 21  job_role                       189 non-null    object
 22  education                      189 non-null    object
 23  work_history                   189 non-null    object
 24  formatting_issues              189 non-null    object
 25  sections.coreCompetencies      189 non-null    object
 26  sections.leadershipManagement  99 non-null     object
 27  sections.certifications        189 non-null    object
 28  sections.languages             189 non-null    object
 29  sections.passportVisaHistory   13 non-null     object
 30  sections.military              1 non-null      object
 31  sections.volunteer             0 non-null      float64
 32  sections.communityWork         0 non-null      float64
 33  additional_sections            176 non-null    object
dtypes: float64(3), int64(3), object(28)
memory usage: 50.3+ KB
None


 first 5 rows — eyeball the data

,0,1,2,3,4
id,2,3,5,11,14
user_id,NaN,NaN,NaN,NaN,NaN
analysis_id,1759998111377,1759998769335,1759999340602,1760001071242,1760001127938
candidate_name,Christopher Davis,Minh Vu,TRAN QUOC BAO,Le Anh Vy (Chloe),Le Anh Vy (Chloe)
email,chris.davis.1990@email.com,vddminh89@gmail.com,21bao.tq@vinuni.edu.vn,chloe@theseedsoft.com,chloe@theseedsoft.com
phone,(415) 555-0776,(84) 090-4562633,(+84) 382780002,0404 262 401,0404 262 401
status,craft,craft,craft,craft,craft
file_name,Christopher Davis_Flutter Developer.pdf,CV_Minh Vu - Minh Vu.pdf,BaoTran_resume - BaÌo TraÌÌn.pdf,Le Anh Vy - CV.PDF,Le Anh Vy - CV.PDF
created_at,2025-10-09T08:22:24,2025-10-09T08:33:36,2025-10-09T08:42:56,2025-10-09T09:12:00,2025-10-09T09:13:11
updated_at,2025-10-09T08:22:24,2025-10-09T08:33:36,2025-10-09T08:42:56,2025-10-09T09:12:00,2025-10-09T09:13:11
overview,Proficient Flutter Developer with 2 years buil...,Seasoned System Manager with 9 years of ERP an...,Electrical Engineering student with research e...,Project Manager with over 18 years in marketin...,Project and program management professional wi...
technical_skills,"[{""name"":""Flutter"",""level"":""Advanced"",""score"":...","[{""name"":""ERP System Evaluation"",""level"":""Adva...","[{""name"":""Python"",""level"":""Advanced"",""score"":8...","[{""name"":""Microsoft Office (Excel, Word, Power...","[{""name"":""Microsoft Office: Excel, Word, Power..."
soft_skills,"[{""name"":""Collaboration"",""level"":""Intermediate...","[{""name"":""Problem solving"",""level"":""Expert"",""s...",[],"[{""name"":""Project Management"",""level"":""Expert""...","[{""name"":""Project Management"",""level"":""Expert""..."
strengths,"[""Proficient Flutter & Dart development"",""Cros...","[""ERP systems implementation with Odoo"",""BI re...","[""Expertise in robust EV charging optimization...","[""Entrepreneurial leadership"",""Cross-continent...","[""Extensive program & project management exper..."
gaps,"[""Generic project description"",""Missing GitHub...","[""Missing professional summary section"",""Lacks...","[""No professional summary or objective stateme...","[""No business analysis keywords"",""Lacks quanti...","[""No quantifiable impact metrics"",""Missing bus..."
keywords,"[""Flutter"",""Dart"",""Firebase"",""RESTful APIs"",""A...","[""ERP"",""Odoo"",""SQL"",""Power BI"",""BI reporting"",...","[""Python"",""Matlab"",""TensorFlow"",""Deep Learning...","[""project management"",""stakeholder engagement""...","[""project management"",""program management"",""co..."
experience_level.level,Mid level,Senior level,Entry level,Executive level,Senior level
experience_level.years,2,9,3,18,18
recommendations,"[""Add actual GitHub project links"",""Quantify a...","[""Add a professional summary highlighting key ...","[""Add a professional summary highlighting AI/M...","[""Quantify achievements (e.g., % growth, budge...","[""Include quantifiable achievements (e.g., rev..."
regional_insights,"[""Australian employers expect local phone form...","[""Use Australian English spelling (e.g., \""opt...","[""Clearly state Australian work rights or visa...","[""Australian employers value PMP/Prince2 or Ag...","[""State Australian work rights or visa status ..."
location,"San Francisco, CA","Hochiminh city, Vietnam","Da Ton, Gia Lam, Hanoi, Vietnam","Bankstown, 2200, NSW","Bankstown, 2200, NSW"
job_role,Flutter development,Data analytics,Artificial intelligence,Business analyst,Business analyst
education,"[""Bachelor of Engineering in Computer Engineer...","[""2022 – 2025 Advanced Diploma in Software Eng...","[""VinUniversity, Gia Lam, Hanoi – Bachelor of ...","[""Advance Diploma of Business, Academy of Entr...","[""Advance Diploma of Business, Academy of Entr..."
work_history,"[""Flutter Developer\nAppMakers Co., London, UK...","[""System Manager\nJYSK Vietnam – Furniture ret...","[""Research Assistant\nCollege of Engineering a...","[""Founder & CEO\nThe Seedsoft PTY LTD | Oct 20...","[""Founder & CEO\nThe Seedsoft PTY LTD, Sydney ..."
formatting_issues,"[""Placeholder GitHub link text"",""LinkedIn URL ...","[""Hyphen and bullet mix inconsistent"",""No unif...","[""Inconsistent date formats across entries"",""J...","[""Bullet styles vary"",""Overseas roles merged b...","[""Inconsistent date format styles"",""Bullet sty..."
sections.coreCompetencies,[],"[""Problem solving"",""Leadership"",""ERP System Ev...","[""Python"",""Matlab"",""TensorFlow"",""React.js"",""Fi...",[],"[""Program Management"",""Project Management"",""Co..."
sections.leadershipManagement,NaN,NaN,NaN,NaN,NaN
sections.certifications,[],[],"[""Deep Learning Specialization, DeepLearning.A...","[""LinkedIN Project Management Certification""]","[""LinkedIN Project Management Certification | ..."
sections.languages,[],[],"[{""language"":""English"",""proficiency"":""Fluent""}]",[],[]
sections.passportVisaHistory,NaN,NaN,NaN,NaN,NaN
sections.military,NaN,NaN,NaN,NaN,NaN
sections.volunteer,NaN,NaN,NaN,NaN,NaN
sections.communityWork,NaN,NaN,NaN,NaN,NaN
additional_sections,NaN,NaN,NaN,NaN,NaN

In [5]:
# last 5 rows — any weird trailing rows?
print(" last 5 rows — any weird trailing rows?")
df.tail(5)

 last 5 rows — any weird trailing rows?

,id,user_id,analysis_id,candidate_name,email,phone,status,file_name,created_at,updated_at,...,formatting_issues,sections.coreCompetencies,sections.leadershipManagement,sections.certifications,sections.languages,sections.passportVisaHistory,sections.military,sections.volunteer,sections.communityWork,additional_sections
184,356,78.0,1770000367449,Nguyễn Ngọc Bảo Trân,nguyenngocbaotran.contact@gmail.com,(+84) 987934364,completed,Nguyen Ngoc bao Tran.pdf,2026-02-02T02:46:47,2026-02-02T02:46:47,...,"[""Inconsistent bullet symbols"",""Date formats v...","[""Java"",""API Testing"",""UX/UI Testing"",""Black-b...",NaN,"[""Manual Testing Certificate, FPT Academy (08/...",[],NaN,NaN,NaN,NaN,"[{""items"":[""09/2022 - Now: Slot Game Quality T..."
185,357,121.0,1770480528604,Abdul Karim,Abdul.karim00035@gmail.com,+966-555168042,craft,Abdul Karim-CV (1).pdf,2026-02-07T16:09:33,2026-02-07T16:09:33,...,"[""Uses horizontal lines disrupting ATS"",""Bulle...","[""Power Plant O&M (CCGT & Cogeneration)"",""Gas ...","Maintenance Team Lead, ASHOMCo – Hawiyah Cogen...","[""APM – Maintenance Manager Certification"",""Pr...",[],NaN,NaN,NaN,NaN,"[{""items"":[""• GE 7FA Gas Turbine Training\n• R..."
186,358,NaN,1770645524167,Phil Dinh,phildinhdata@gmail.com,0451 840 818,craft,Data Analyst - Resume - Phil Dinh.pdf,2026-02-09T13:59:27,2026-02-09T13:59:27,...,"[""Inconsistent dash styles in dates"",""Sub-bull...","[""Data-Driven & Customer Success Focus"",""Probl...",NaN,[],[],NaN,NaN,NaN,NaN,"[{""items"":[""Retail Sales Performance Dashboard..."
187,359,122.0,1770645573729,PHIL DINH,phildinhdata@gmail.com,0451 840 818,craft,Data Analyst - Resume - Phil Dinh.pdf,2026-02-09T14:00:03,2026-02-09T14:00:03,...,"[""Inconsistent indentation for sub-bullets"",""M...","[""Data-Driven & Customer Success Focus"",""Probl...",NaN,[],[],NaN,NaN,NaN,NaN,"[{""items"":[""Retail Sales Performance Dashboard..."
188,362,107.0,1771904249832,Tai Nguyen,nguyenductaidhsp@gmail.com,(+84) 907959003,completed,SSE_Nguyen_Duc_Tai_AU_012026.pdf,2026-02-24T03:38:19,2026-02-24T03:38:19,...,"[""Inconsistent date format styles"",""Summary is...","[""Core Engineering & System Design"",""Cloud, De...","Senior Software Engineer (Expert-level), SMG (...","[""AWS Certified Solutions Architect – Associat...","[{""language"":""English"",""proficiency"":""Fluent""}]",Actively seeking employer-sponsored opportunit...,NaN,NaN,NaN,[]

In [6]:
# random 5 rows — avoids being fooled by "clean" top rows
print(" random 5 rows — avoids being fooled by 'clean' top rows")
df.sample(5)

 random 5 rows — avoids being fooled by 'clean' top rows

,id,user_id,analysis_id,candidate_name,email,phone,status,file_name,created_at,updated_at,...,formatting_issues,sections.coreCompetencies,sections.leadershipManagement,sections.certifications,sections.languages,sections.passportVisaHistory,sections.military,sections.volunteer,sections.communityWork,additional_sections
127,240,NaN,1765334240405,Thai Thinh,thinhpt11211@gmail.com,0383799926,craft,Thiáº¿t káº¿ chÆ°a cÃ³ tÃªn_20251210_093522_00...,2025-12-10T02:37:51,2025-12-10T02:37:51,...,"[""Mixed hyphens and bullets"",""Inconsistent dat...","[""Leadership and Management: Leadership, team ...","Class President, University of Economics and F...","[""Hospitality Mastery: From personalized servi...","[{""language"":""Vietnamese"",""proficiency"":""Nativ...",NaN,NaN,NaN,NaN,[]
173,333,NaN,1768310941998,La Thi Phuong Thao,lathiphuongthao.contact@gmail.com,(+84) 987934364,craft,LaThiPhuongThao_CV.pdf,2026-01-13T13:29:35,2026-01-13T13:29:35,...,"[""Inconsistent date formats"",""Missing bullet f...","[""Java"",""API Testing"",""UX/UI Testing"",""Black-b...",NaN,"[""2019-2023: Software Engineering at Thu Dau M...",[],NaN,NaN,NaN,NaN,[]
21,61,NaN,1760256028351,Pham Thi Nhu Y,yphamcr@gmail.com,+84 906 636 911,craft,CV-Pham-Thi-Nhu-Y-21101988.pdf,2025-10-12T08:01:12,2025-10-12T08:01:12,...,"[""Typo in \""Criris management\"""",""Photo may af...","[""Event Marketing"",""Branding & PR"",""Creativity...",NaN,[],"[{""language"":""Vietnamese"",""proficiency"":""""},{""...",NaN,NaN,NaN,NaN,"[{""items"":[""With a decade of experience in the..."
187,359,122.0,1770645573729,PHIL DINH,phildinhdata@gmail.com,0451 840 818,craft,Data Analyst - Resume - Phil Dinh.pdf,2026-02-09T14:00:03,2026-02-09T14:00:03,...,"[""Inconsistent indentation for sub-bullets"",""M...","[""Data-Driven & Customer Success Focus"",""Probl...",NaN,[],[],NaN,NaN,NaN,NaN,"[{""items"":[""Retail Sales Performance Dashboard..."
76,145,41.0,1760689493510,Tran Huynh Thien Phuc,thienphuctranhuynh2@gmail.com,0582.216.155,completed,Tran Huynh Thien Phuc_CV Resume.pdf.pdf,2025-10-17T08:25:26,2025-10-17T08:25:26,...,"[""Date ranges use inconsistent spacing"",""Phone...","[""English communication"",""Office informatics (...","Co-founder, S4U Media Club (2024 – 2025)\n• Co...",[],[],NaN,NaN,NaN,NaN,[]

#### Step 2 — Understand nulls
"What's missing and how bad is it?"

In [7]:
# count of nulls per column
# null % per column — more useful
# only show columns that HAVE nulls

In [8]:
# count of nulls per column
print("# count of nulls per column")
print(df.isnull().sum())

# count of nulls per column
id                                 0
user_id                          126
analysis_id                        0
candidate_name                     9
email                             17
phone                             20
status                             0
file_name                          0
created_at                         0
updated_at                         0
overview                           6
technical_skills                   0
soft_skills                        0
strengths                          0
gaps                               0
keywords                           0
experience_level.level             5
experience_level.years             0
recommendations                    0
regional_insights                  0
location                          33
job_role                           0
education                          0
work_history                       0
formatting_issues                  0
sections.coreCompetencies          0
sections.leadershipManagement     90
sections.certifications            0
sections.languages                 0
sections.passportVisaHistory     176
sections.military                188
sections.volunteer               189
sections.communityWork           189
additional_sections               13
dtype: int64

In [9]:
# null % per column — more useful
print("# null % per column — more useful")
columns_null = (df.isnull().sum() / len(df) * 100).sort_values(ascending=False)

# only show columns that HAVE nulls
print("# only show columns that HAVE nulls")
print(columns_null[columns_null>0])

# null % per column — more useful
# only show columns that HAVE nulls
sections.volunteer               100.000000
sections.communityWork           100.000000
sections.military                 99.470899
sections.passportVisaHistory      93.121693
user_id                           66.666667
sections.leadershipManagement     47.619048
location                          17.460317
phone                             10.582011
email                              8.994709
additional_sections                6.878307
candidate_name                     4.761905
overview                           3.174603
experience_level.level             2.645503
dtype: float64

#### Step 3 — Understand unique values in categorical columns
"Are there duplicates, typos, inconsistent casing?"

In [10]:
# frequency of each value
# spot trailing spaces, casing issues
# how many unique values?
# list them all

In [11]:
# Check all columns name
print("All columns do we have, then we can identify the category")
df.columns

All columns do we have, then we can identify the category

Index(['id', 'user_id', 'analysis_id', 'candidate_name', 'email', 'phone',
       'status', 'file_name', 'created_at', 'updated_at', 'overview',
       'technical_skills', 'soft_skills', 'strengths', 'gaps', 'keywords',
       'experience_level.level', 'experience_level.years', 'recommendations',
       'regional_insights', 'location', 'job_role', 'education',
       'work_history', 'formatting_issues', 'sections.coreCompetencies',
       'sections.leadershipManagement', 'sections.certifications',
       'sections.languages', 'sections.passportVisaHistory',
       'sections.military', 'sections.volunteer', 'sections.communityWork',
       'additional_sections'],
      dtype='object')

In [12]:
# frequency of each value
print("# frequency of each value")
print(df["status"].value_counts())
print("\n")

# spot trailing spaces, casing issues
print("# spot trailing spaces, casing issues")
print(df['job_role'].value_counts())
print("\n")

# how many unique values?
print("# how many unique values? in experience level")
print(df['experience_level.level'].nunique())
print("\n")

# list them all
print("# how many unique values? in experience level")
print(df['experience_level.level'].unique())

# frequency of each value
status
craft        145
completed     44
Name: count, dtype: int64


# spot trailing spaces, casing issues
job_role
Marketing Specialist                          45
Test engineering                              42
Business analyst                              20
Data analytics                                15
Accommodation and Hospitality Managers nec    13
Business analyst                              10
Content Creator (Marketing)                    9
Hotel or Motel Manager                         8
Front-end web development                      8
Artificial intelligence                        7
Back-end web development                       6
Public Relations Professional                  3
Data engineering                               2
Flutter development                            1
Name: count, dtype: int64


# how many unique values? in experience level
10


# how many unique values? in experience level
['Mid level' 'Senior level' 'Entry level' 'Executive level' 'Expert level'
 nan 'Expert' 'Senior' 'Mid' 'Lead' 'Entry']

#### Step 4 — Understand numeric columns
"What's the range, are there outliers, do the numbers make sense?"

In [13]:
df.describe()

,id,user_id,analysis_id,experience_level.years,sections.volunteer,sections.communityWork
count,189.000000,63.000000,1.890000e+02,189.000000,0.0,0.0
mean,184.783069,62.666667,1.763338e+12,5.661376,NaN,NaN
std,98.975446,39.682612,3.347436e+09,6.342330,NaN,NaN
min,2.000000,1.000000,1.759998e+12,0.000000,NaN,NaN
25%,112.000000,17.500000,1.760689e+12,1.000000,NaN,NaN
50%,182.000000,72.000000,1.761300e+12,3.000000,NaN,NaN
75%,258.000000,97.500000,1.765810e+12,7.000000,NaN,NaN
max,362.000000,122.000000,1.771904e+12,22.000000,NaN,NaN

#### Step 5 — Spot structural/data quality issues
"What columns need special treatment?"

In [14]:
# Check for duplicate rows, # total duplicate rows
# Check for duplicates on a key column

In [15]:
# Check for duplicate rows, # total duplicate rows
print("# Check for duplicate rows, # total duplicate rows")
print("Total duplicate rows: ", df.duplicated().sum())
print("\n")

# Check for duplicates on a key column
for s in ['id', 'user_id', 'analysis_id', 'candidate_name', 'email', 'phone','file_name']:
    if s in df.columns:
        dup_count = df[s].duplicated().sum()
        null_count = df[s].isnull().sum()
        print(f"{s:<20} | duplicates: {dup_count:<5} | nulls: {null_count}")

# Check for duplicate rows, # total duplicate rows
Total duplicate rows:  0


id                   | duplicates: 0     | nulls: 0
user_id              | duplicates: 125   | nulls: 126
analysis_id          | duplicates: 0     | nulls: 0
candidate_name       | duplicates: 85    | nulls: 9
email                | duplicates: 85    | nulls: 17
phone                | duplicates: 93    | nulls: 20
file_name            | duplicates: 72    | nulls: 0

In [16]:
# After finding email has duplicates, inspect them
df[df['email'].duplicated(keep=False)].sort_values('email')[['id', 'analysis_id', 'candidate_name', 'email', 'created_at', 'file_name']]

,id,analysis_id,candidate_name,email,created_at,file_name
2,5,1759999340602,TRAN QUOC BAO,21bao.tq@vinuni.edu.vn,2025-10-09T08:42:56,BaoTran_resume - BaÌo TraÌÌn.pdf
7,17,1760001555963,TRAN QUOC BAO,21bao.tq@vinuni.edu.vn,2025-10-09T09:19:50,BaoTran_resume - BaÌo TraÌÌn.pdf
63,130,1760688965820,Nguyễn Thiện Nhân,78thiennhan78@gmail.com,2025-10-17T08:16:45,CV and Cover letter - Nguyá» n Thiá»n NhÃ¢n....
69,136,1760689008868,Nguyễn Thiện Nhân,78thiennhan78@gmail.com,2025-10-17T08:17:27,CV and Cover letter - Nguyá» n Thiá»n NhÃ¢n....
29,80,1760502219404,Nguyen Phat Tai,abc@gmail.com,2025-10-15T04:24:06,BA_contain photo_CV.docx
...,...,...,...,...,...,...
151,284,1766970531512,NaN,NaN,2025-12-29T01:09:24,QC_1.pdf
152,285,1766970593003,NaN,NaN,2025-12-29T01:10:17,QC_1.pdf
165,321,1768228269914,NaN,NaN,2026-01-12T14:31:16,Empty CV.docx
174,341,1769052233511,Tran Tuyet Ngoc,NaN,2026-01-22T03:24:57,Tran Tuyet Ngoc Resume.pdf
180,352,1769496132126,Tran Tuyet Ngoc,NaN,2026-01-27T06:42:56,Tran Tuyet Ngoc Resume.pdf

#### 5. Check the JSON-like columns

In [40]:
# Look at the raw value — what format is it actually?
print(df['technical_skills'].iloc[0]) # this is json string
print(df['education'].iloc[0]) # list
print(df['work_history'].iloc[0]) # list

[{"name":"Flutter","level":"Advanced","score":85},{"name":"Dart","level":"Advanced","score":80},{"name":"Swift","level":"Intermediate","score":60},{"name":"Kotlin","level":"Intermediate","score":60},{"name":"Provider","level":"Intermediate","score":65},{"name":"BLoC","level":"Intermediate","score":65},{"name":"Riverpod","level":"Intermediate","score":65},{"name":"Android Studio","level":"Intermediate","score":70},{"name":"VS Code","level":"Intermediate","score":70},{"name":"Xcode","level":"Intermediate","score":65},{"name":"Git","level":"Advanced","score":75},{"name":"Firebase","level":"Intermediate","score":70},{"name":"SQLite","level":"Intermediate","score":60},{"name":"RESTful APIs","level":"Intermediate","score":70},{"name":"JSON","level":"Intermediate","score":70},{"name":"Agile/Scrum","level":"Intermediate","score":65}]
["Bachelor of Engineering in Computer Engineering Imperial College London | London, UK Graduated: June 2021"]
["Flutter Developer\nAppMakers Co., London, UK | October 2022 – Present\n• Developed and launched a social networking app using Flutter, available on both the App Store and Google Play.\n• Implemented features such as real-time chat, push notifications, and user authentication using Firebase.\n• Collaborated with the design team to create a pixel-perfect user interface that matched the mockups.\n• Wrote clean and maintainable code following best practices for Flutter development.","Junior Mobile Developer\nMobile Innovations, London, UK | August 2021 – September 2022\n• Assisted in the development of native Android and iOS applications.\n• Gained experience with mobile app testing and debugging.\n• Contributed to the maintenance and improvement of existing mobile apps."]

In [41]:
# Check if ALL rows have this format or some are plain text / empty
df['technical_skills'].apply(type).value_counts()  # are they all strings?
df['technical_skills'].apply(lambda x: str(x).startswith('[')).value_counts()  # list format?

# Every single row (189/189) stores `technical_skills` as a list format. **No surprises, no mixed formats.** This means you can safely parse all rows the same way later.

technical_skills
True    189
Name: count, dtype: int64

### 2. Make customer Dim

In [19]:
df.columns

Index(['id', 'user_id', 'analysis_id', 'candidate_name', 'email', 'phone',
       'status', 'file_name', 'created_at', 'updated_at', 'overview',
       'technical_skills', 'soft_skills', 'strengths', 'gaps', 'keywords',
       'experience_level.level', 'experience_level.years', 'recommendations',
       'regional_insights', 'location', 'job_role', 'education',
       'work_history', 'formatting_issues', 'sections.coreCompetencies',
       'sections.leadershipManagement', 'sections.certifications',
       'sections.languages', 'sections.passportVisaHistory',
       'sections.military', 'sections.volunteer', 'sections.communityWork',
       'additional_sections'],
      dtype='object')

In [20]:
df['education'].iloc[0]

'["Bachelor of Engineering in Computer Engineering Imperial College London | London, UK Graduated: June 2021"]'

In [21]:
# Make a copy for dim customer, we won't work with our df dataset
df1 = df[["candidate_name","email","phone","location","education","file_name","created_at","experience_level.level","experience_level.years","job_role"]].copy()
df1.head().T

,0,1,2,3,4
candidate_name,Christopher Davis,Minh Vu,TRAN QUOC BAO,Le Anh Vy (Chloe),Le Anh Vy (Chloe)
email,chris.davis.1990@email.com,vddminh89@gmail.com,21bao.tq@vinuni.edu.vn,chloe@theseedsoft.com,chloe@theseedsoft.com
phone,(415) 555-0776,(84) 090-4562633,(+84) 382780002,0404 262 401,0404 262 401
location,"San Francisco, CA","Hochiminh city, Vietnam","Da Ton, Gia Lam, Hanoi, Vietnam","Bankstown, 2200, NSW","Bankstown, 2200, NSW"
education,"[""Bachelor of Engineering in Computer Engineer...","[""2022 – 2025 Advanced Diploma in Software Eng...","[""VinUniversity, Gia Lam, Hanoi – Bachelor of ...","[""Advance Diploma of Business, Academy of Entr...","[""Advance Diploma of Business, Academy of Entr..."
file_name,Christopher Davis_Flutter Developer.pdf,CV_Minh Vu - Minh Vu.pdf,BaoTran_resume - BaÌo TraÌÌn.pdf,Le Anh Vy - CV.PDF,Le Anh Vy - CV.PDF
created_at,2025-10-09T08:22:24,2025-10-09T08:33:36,2025-10-09T08:42:56,2025-10-09T09:12:00,2025-10-09T09:13:11
experience_level.level,Mid level,Senior level,Entry level,Executive level,Senior level
experience_level.years,2,9,3,18,18
job_role,Flutter development,Data analytics,Artificial intelligence,Business analyst,Business analyst

In [22]:
# Check duplicated for 3 keys values, candidate_name, email and phone
print("Check duplicated value with simple information: ")
print(df1.duplicated(subset=["candidate_name","email","phone","location"]).sum())
print("Check duplicated value with more information: ")
print(df1.duplicated(subset=["candidate_name","email","phone","location","experience_level.level","experience_level.years","job_role"]).sum())

Check duplicated value with simple information:
60
Check duplicated value with more information:
35

In [23]:
# Find the rows where same person has different job_role
dupes = df1[df1.duplicated(subset=["candidate_name","email","phone","location"],keep=False)]
dupes.sort_values('candidate_name')[['candidate_name','email','job_role','experience_level.level','created_at']]

,candidate_name,email,job_role,experience_level.level,created_at
5,Amanda Martinez,amanda.martinez@email.com,Data engineering,Senior level,2025-10-09T09:18:42
33,Amanda Martinez,amanda.martinez@email.com,Data engineering,Senior level,2025-10-16T08:02:31
26,DUNG DAO,dungdao.dev@example.com,Back-end web development,Senior level,2025-10-14T09:52:52
163,DUNG DAO,dungdao.dev@example.com,Back-end web development,Lead,2026-01-12T14:26:36
90,DUNG VŨ ĐÀO,dungdao.dev@example.com,Back-end web development,Senior level,2025-10-20T10:42:28
...,...,...,...,...,...
149,NaN,NaN,Test engineering,Senior,2025-12-29T01:02:34
150,NaN,NaN,Test engineering,Senior,2025-12-29T01:08:22
151,NaN,NaN,Test engineering,Mid,2025-12-29T01:09:24
152,NaN,NaN,Test engineering,Senior,2025-12-29T01:10:17
165,NaN,NaN,Front-end web development,NaN,2026-01-12T14:31:16

It is very important to check carefully how each rows in dataset indicates values and meaning. We can see same people but they have different job role and experience level with date as well. So we decide to take dim_customer has stable attributes only

In [24]:
df_customer = df[["candidate_name","email","phone","location","education"]].copy()
df_customer.head().T

,0,1,2,3,4
candidate_name,Christopher Davis,Minh Vu,TRAN QUOC BAO,Le Anh Vy (Chloe),Le Anh Vy (Chloe)
email,chris.davis.1990@email.com,vddminh89@gmail.com,21bao.tq@vinuni.edu.vn,chloe@theseedsoft.com,chloe@theseedsoft.com
phone,(415) 555-0776,(84) 090-4562633,(+84) 382780002,0404 262 401,0404 262 401
location,"San Francisco, CA","Hochiminh city, Vietnam","Da Ton, Gia Lam, Hanoi, Vietnam","Bankstown, 2200, NSW","Bankstown, 2200, NSW"
education,"[""Bachelor of Engineering in Computer Engineer...","[""2022 – 2025 Advanced Diploma in Software Eng...","[""VinUniversity, Gia Lam, Hanoi – Bachelor of ...","[""Advance Diploma of Business, Academy of Entr...","[""Advance Diploma of Business, Academy of Entr..."

In [25]:
# As we can see same people but location is different. The problem comes from system because we don't Force login/registration → fixed customer profile
dupes = df_customer[df_customer.duplicated(subset=['candidate_name', 'email', 'phone'], keep=False)]
dupes.sort_values('email')

,candidate_name,email,phone,location,education
2,TRAN QUOC BAO,21bao.tq@vinuni.edu.vn,(+84) 382780002,"Da Ton, Gia Lam, Hanoi, Vietnam","[""VinUniversity, Gia Lam, Hanoi – Bachelor of ..."
7,TRAN QUOC BAO,21bao.tq@vinuni.edu.vn,(+84) 382780002,"Da Ton, Gia Lam, Hanoi","[""VinUniversity, Gia Lam, Hanoi | Bachelor of ..."
63,Nguyễn Thiện Nhân,78thiennhan78@gmail.com,0833070804,NaN,"[""University of Economics and Finance | 10/202..."
69,Nguyễn Thiện Nhân,78thiennhan78@gmail.com,0833070804,NaN,"[""University of Economics and Finance, 10/2022..."
25,Nguyen Phat Tai,abc@gmail.com,+84 999999999,"Sydney, AU","[""Bachelor of Information Technology – Univers..."
...,...,...,...,...,...
151,NaN,NaN,NaN,NaN,"[""Information Technology\nHo Chi Minh Universi..."
152,NaN,NaN,NaN,NaN,"[""Information Technology, Ho Chi Minh Universi..."
165,NaN,NaN,NaN,NaN,[]
174,Tran Tuyet Ngoc,NaN,NaN,NaN,"[""Certificate Diploma Language Programmer of U..."
180,Tran Tuyet Ngoc,NaN,NaN,NaN,"[""Certificate Diploma Language Programmer of U..."

In [26]:
df_customer["candidate_name"] = df_customer["candidate_name"].str.lower().str.strip()
df_customer["email"] = df_customer["email"].str.lower().str.strip()
# Step 2 — remove everything except digits
df_customer['phone'] = df_customer['phone'].str.replace(r'[^0-9]', '', regex=True).str.strip()

In [27]:
# Check email invalid
df_customer["email_valid"] = df_customer["email"].str.match(r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$')

# Check how many are invalid
df_customer["email_valid"].value_counts()

# Look at the invalid ones
df_customer[df_customer["email_valid"] == False]["email"]

Series([], Name: email, dtype: object)

In [28]:
# Check 1 — how many are actually NULL
df_customer['email'].isnull().sum()

np.int64(17)

In [29]:
# So in here we will deduplicated as keep first value
dim_customer = df_customer.drop_duplicates(subset=['candidate_name', 'email', 'phone'], keep='first')
dim_customer

,candidate_name,email,phone,location,education,email_valid
0,christopher davis,chris.davis.1990@email.com,4155550776,"San Francisco, CA","[""Bachelor of Engineering in Computer Engineer...",True
1,minh vu,vddminh89@gmail.com,840904562633,"Hochiminh city, Vietnam","[""2022 – 2025 Advanced Diploma in Software Eng...",True
2,tran quoc bao,21bao.tq@vinuni.edu.vn,84382780002,"Da Ton, Gia Lam, Hanoi, Vietnam","[""VinUniversity, Gia Lam, Hanoi – Bachelor of ...",True
3,le anh vy (chloe),chloe@theseedsoft.com,0404262401,"Bankstown, 2200, NSW","[""Advance Diploma of Business, Academy of Entr...",True
5,amanda martinez,amanda.martinez@email.com,6025550811,"Phoenix, AZ","[""Master of Science in Data Science University...",True
...,...,...,...,...,...,...
177,hoàng minh ngọc hải,hoangminhngochai@gmail.com,84916888143,Hồ Chí Minh City,"[""Tôn Đức Thắng University, Software Engineeri...",True
178,nguyễn ngọc bảo trân,nguyennogcbaotran.contact@gmail.com,84987934364,"District 7, Ho Chi Minh City, Vietnam","[""Tôn Đức Thắng University, Software Engineeri...",True
185,abdul karim,abdul.karim00035@gmail.com,966555168042,Saudi Arabia,"[""Bachelor of Engineering (Mechanical), Mehran...",True
186,phil dinh,phildinhdata@gmail.com,0451840818,"Sydney, Australia","[""Data Analytics Training Program, Sydney | Au...",True
188,tai nguyen,nguyenductaidhsp@gmail.com,84907959003,"Ho Chi Minh City, Vietnam","[""Bachelors | Ho Chi Minh City University of P...",True

In [30]:
# Check shape after deduplication
dim_customer.shape

(112, 6)

In [31]:
# reset_index makes it clean 0,1,2,3,4...
dim_customer = dim_customer.reset_index(drop=True)

# Now generate customer_id
dim_customer['customer_id'] = dim_customer.index + 1
dim_customer

,candidate_name,email,phone,location,education,email_valid,customer_id
0,christopher davis,chris.davis.1990@email.com,4155550776,"San Francisco, CA","[""Bachelor of Engineering in Computer Engineer...",True,1
1,minh vu,vddminh89@gmail.com,840904562633,"Hochiminh city, Vietnam","[""2022 – 2025 Advanced Diploma in Software Eng...",True,2
2,tran quoc bao,21bao.tq@vinuni.edu.vn,84382780002,"Da Ton, Gia Lam, Hanoi, Vietnam","[""VinUniversity, Gia Lam, Hanoi – Bachelor of ...",True,3
3,le anh vy (chloe),chloe@theseedsoft.com,0404262401,"Bankstown, 2200, NSW","[""Advance Diploma of Business, Academy of Entr...",True,4
4,amanda martinez,amanda.martinez@email.com,6025550811,"Phoenix, AZ","[""Master of Science in Data Science University...",True,5
...,...,...,...,...,...,...,...
107,hoàng minh ngọc hải,hoangminhngochai@gmail.com,84916888143,Hồ Chí Minh City,"[""Tôn Đức Thắng University, Software Engineeri...",True,108
108,nguyễn ngọc bảo trân,nguyennogcbaotran.contact@gmail.com,84987934364,"District 7, Ho Chi Minh City, Vietnam","[""Tôn Đức Thắng University, Software Engineeri...",True,109
109,abdul karim,abdul.karim00035@gmail.com,966555168042,Saudi Arabia,"[""Bachelor of Engineering (Mechanical), Mehran...",True,110
110,phil dinh,phildinhdata@gmail.com,0451840818,"Sydney, Australia","[""Data Analytics Training Program, Sydney | Au...",True,111
111,tai nguyen,nguyenductaidhsp@gmail.com,84907959003,"Ho Chi Minh City, Vietnam","[""Bachelors | Ho Chi Minh City University of P...",True,112

##### Work with location, we will split to country and city

In [32]:
# How many values do we have
dim_customer["location"].value_counts()

location
Ho Chi Minh City, Vietnam                11
District 7, Ho Chi Minh City, Vietnam     5
Ho Chi Minh City                          3
Sydney                                    3
San Francisco, CA                         2
                                         ..
Thu Duc, TPHCM                            1
TP Hồ Chí Minh                            1
Hà Nội, Việt Nam                          1
Hồ Chí Minh City                          1
Saudi Arabia                              1
Name: count, Length: 69, dtype: int64

In [33]:
# How many nan values do we have
dim_customer["location"].isnull().sum()

np.int64(16)

In [34]:
dim_customer["country"] = dim_customer["location"].str.split(',').str[-1].str.strip().str.lower()
dim_customer['city'] = dim_customer['location'].str.split(',').apply(
    lambda x: ', '.join(x[:-1]).strip() if isinstance(x, list) else None
).str.lower()

In [35]:
dim_customer.head(10)

,candidate_name,email,phone,location,education,email_valid,customer_id,country,city
0,christopher davis,chris.davis.1990@email.com,4155550776,"San Francisco, CA","[""Bachelor of Engineering in Computer Engineer...",True,1,ca,san francisco
1,minh vu,vddminh89@gmail.com,840904562633,"Hochiminh city, Vietnam","[""2022 – 2025 Advanced Diploma in Software Eng...",True,2,vietnam,hochiminh city
2,tran quoc bao,21bao.tq@vinuni.edu.vn,84382780002,"Da Ton, Gia Lam, Hanoi, Vietnam","[""VinUniversity, Gia Lam, Hanoi – Bachelor of ...",True,3,vietnam,"da ton, gia lam, hanoi"
3,le anh vy (chloe),chloe@theseedsoft.com,0404262401,"Bankstown, 2200, NSW","[""Advance Diploma of Business, Academy of Entr...",True,4,nsw,"bankstown, 2200"
4,amanda martinez,amanda.martinez@email.com,6025550811,"Phoenix, AZ","[""Master of Science in Data Science University...",True,5,az,phoenix
5,arshad manivannan,arshadrehman2628@gmail.com,0451762826,"Melbourne, Victoria - 3073","[""Master of Networking - Major in Cyber Securi...",True,6,victoria - 3073,melbourne
6,shara will,shara.will@gmail.com,15551234567,"HCM, Viet Nam","[""Diploma [University of Natural Science] Dipl...",True,7,viet nam,hcm
7,richard sanchez,noemailprovided@example.com,NaN,NaN,"[""Degree\nInstitution | YYYY - YYYY\n• Major/S...",True,8,NaN,None
8,truc nguyen,truc.nguyen1704@gmail.com,84937712575,NaN,"[""2003 – 2007 BA Degree in Literature & Journa...",True,9,NaN,None
9,foo lee,shara.will@email.com,84912345678,"Ho Chi Minh City, Vietnam","[""Bachelor’s Degree in Information Technology ...",True,10,vietnam,ho chi minh city

In [36]:
# We work with country column first
dim_customer["country"].unique()

array(['ca', 'vietnam', 'nsw', 'az', 'victoria - 3073', 'viet nam', nan,
       'usa', 'hanoi', 'sydney', 'au', 'wa', '2017', 'qld 4006',
       'ho chi minh city', '118/6 le loi p4 go vap', 'district 8',
       'go vap', 'hcm city', 'vietnam.', 'tp.hcm',
       '164 duong quang ham/go vap/ho chi minh city', 'tp. hcm',
       'lords av. asquith nsw 2077', 'nsw 2165', 'australia', '5000',
       '6059', 'oh', 'aus', 'qld 4000', 'nsw 2122', 'hcmc', 'vic', 'vn',
       'united states', 'tphcm', 'hcm', 'tp hồ chí minh', 'việt nam',
       'hồ chí minh city', 'saudi arabia'], dtype=object)

In [37]:
# Use np.select() with str.contains()
# e.g. user typed locations, inconsistent formats
conditions = [
    # Australia — add sydney, postcodes
    dim_customer['country'].str.contains(
        'nsw|vic|qld|australia|victoria|wa|sydney|aus', 
        case=False, na=False
    ) | dim_customer['country'].str.strip().str.lower().isin(['au', '5000', '6059', '2017']),

    # Vietnam — add unicode + missed patterns
    dim_customer['country'].str.contains(
        'hcm|vietnam|viet nam|ho chi minh|district|hanoi|tphcm|việt nam|hồ chí minh|go vap|le loi|tp hồ',
        case=False, na=False
    ) | dim_customer['country'].str.strip().str.lower().isin(['vn']),

    # United States
    dim_customer['country'].str.contains('usa|united states', case=False, na=False),

    # United States exact codes
    dim_customer['country'].str.strip().str.lower().isin(['ca', 'az', 'oh']),

    # Saudi Arabia
    dim_customer['country'].str.strip().str.lower().isin(['saudi arabia'])
]

choices = ['Australia', 'Vietnam', 'United States', 'United States','Saudi Arabia']

In [38]:
dim_customer['country_clean'] = np.select(conditions,choices,default='Unknown')
dim_customer['country_clean'].value_counts()

country_clean
Vietnam          62
Australia        27
Unknown          16
United States     6
Saudi Arabia      1
Name: count, dtype: int64

In [39]:
# Show the original country values that ended up as Unknown, that's good.
dim_customer[dim_customer['country_clean'] == 'Unknown']

,candidate_name,email,phone,location,education,email_valid,customer_id,country,city,country_clean
7,richard sanchez,noemailprovided@example.com,NaN,NaN,"[""Degree\nInstitution | YYYY - YYYY\n• Major/S...",True,8,NaN,None,Unknown
8,truc nguyen,truc.nguyen1704@gmail.com,84937712575,NaN,"[""2003 – 2007 BA Degree in Literature & Journa...",True,9,NaN,None,Unknown
11,richard sanchez,NaN,NaN,NaN,"[""Degree\nInstitution | YYYY - YYYY\n• Major/S...",NaN,12,NaN,None,Unknown
14,hồ thị phương dung,NaN,NaN,NaN,[],NaN,15,NaN,None,Unknown
24,trinh vo hai long,tvhlong@gmail.com,84862479718,NaN,"[""2019 – 2024: Earlham College – Bachelor of A...",True,25,NaN,None,Unknown
27,NaN,NaN,NaN,NaN,[],NaN,28,NaN,None,Unknown
29,huynh ngoc nhu,nhuhn21@uef.edu.vn,0774098238,NaN,"[""University of Economics and Finance (UEF) • ...",True,30,NaN,None,Unknown
30,huynh ngoc nhu,nhuhhn21@uef.edu.vn,0774098238,NaN,"[""University of Economics and Finance (UEF) • ...",True,31,NaN,None,Unknown
43,nguyễn thiện nhân,78thiennhan78@gmail.com,0833070804,NaN,"[""University of Economics and Finance | 10/202...",True,44,NaN,None,Unknown
46,bao phuc,diepphambaophuc@gmail.com,0703244424,NaN,"[""University of Economics and Finance\nMarketi...",True,47,NaN,None,Unknown
54,nguyen thao nhi,nguyenthaonhi769@gmail.com,0865074905,NaN,"[""2022–2026 University of Economics and Financ...",True,55,NaN,None,Unknown
69,tu dai hung,vinhnguyen.tu@ed2career.edu.vn,0938198628,NaN,"[""LCCI – London Chamber of Commerce and Indust...",True,70,NaN,None,Unknown
81,sadashiv babbar,s.babbar@student.unsw.edu.au,NaN,NaN,"[""Bachelors in Computer Science, UNSW, 2026 – ...",True,82,NaN,None,Unknown
82,vanessa (van trang) nguyen,tranghcvismo@gmail.com,0430026595,NaN,"[""Macquarie University, Bachelor of Informatio...",True,83,NaN,None,Unknown
89,tran tuyet ngoc,NaN,NaN,NaN,"[""Certificate Diploma Language Programmer of U...",NaN,90,NaN,None,Unknown
98,đồng trần khánh an,qhoang@example.net,33222496952,NaN,"[""* FPT Highschool Danang\n• Grade 10 GPA: 9.1...",True,99,NaN,None,Unknown

In [46]:
unknown_mask = dim_customer['country_clean'] == 'Unknown'

conditions_phone = [
    dim_customer["phone"].str.startswith("84", na=False),
    dim_customer["phone"].str.startswith(("07","08","09"), na=False),
    dim_customer["phone"].str.startswith("04", na=False),
    dim_customer["phone"].str.startswith("33", na=False),
]

choices_phone = ['Vietnam', 'Vietnam', 'Australia', 'France']

dim_customer.loc[unknown_mask, 'country_clean'] = np.select(
    conditions_phone,
    choices_phone,
    default='Unknown'
)[unknown_mask]

In [ ]:
# Double check again
dim_customer['country_clean'].value_counts()

country_clean
Vietnam          70
Australia        28
United States     6
Unknown           6
France            1
Saudi Arabia      1
Name: count, dtype: int64

In [ ]:
# Double check the Nan value we can not identify
dim_customer[dim_customer['country_clean'] == 'Unknown']

,candidate_name,email,phone,location,education,email_valid,customer_id,country,city,country_clean
7,richard sanchez,noemailprovided@example.com,NaN,NaN,"[""Degree\nInstitution | YYYY - YYYY\n• Major/S...",True,8,NaN,None,Unknown
11,richard sanchez,NaN,NaN,NaN,"[""Degree\nInstitution | YYYY - YYYY\n• Major/S...",NaN,12,NaN,None,Unknown
14,hồ thị phương dung,NaN,NaN,NaN,[],NaN,15,NaN,None,Unknown
27,NaN,NaN,NaN,NaN,[],NaN,28,NaN,None,Unknown
81,sadashiv babbar,s.babbar@student.unsw.edu.au,NaN,NaN,"[""Bachelors in Computer Science, UNSW, 2026 – ...",True,82,NaN,None,Unknown
89,tran tuyet ngoc,NaN,NaN,NaN,"[""Certificate Diploma Language Programmer of U...",NaN,90,NaN,None,Unknown

Working with city

In [49]:
dim_customer["city"].value_counts()

city
                                                              16
ho chi minh city                                              11
district 7,  ho chi minh city                                  5
melbourne                                                      4
sydney                                                         4
hochiminh city                                                 2
binh thanh district                                            2
marsfield                                                      2
ho chi minh                                                    2
tan phu,  ho chi minh city                                     2
adelaide,  australia                                           2
san francisco                                                  2
phoenix                                                        1
bankstown,  2200                                               1
waterloo,  nsw                                                 1
86 bramston terrace,  herston                                  1
da ton,  gia lam,  hanoi                                       1
hcm                                                            1
bac tu liem                                                    1
garden grove,  ca                                              1
109 cao dat,  w1,  d5,  hcmc                                   1
seattle                                                        1
283 bong sao,  ward 5                                          1
phuoc long a ward,  thu duc                                    1
nguyen xi street,  binh thanh district                         1
phường tân sơn nhất,  thành phố hồ chí minh                    1
woolgoolga,  nsw,  australia; ho chi minh city                 1
woolgoolga,  nsw; ho chi minh city                             1
street no. 18,  ward 8                                         1
van kiep street,  gia dinh ward                                1
dong hoa ward                                                  1
15a                                                            1
district 6                                                     1
fairfield                                                      1
88 nguyen van quy,  p. phu thuan                               1
nguyễn văn tạo,  long thới ward,  nhà bè district,  hcmc       1
153/10 nguyen thi minh khai st,  ben thanh ward,  hcmc         1
binh thanh                                                     1
cleveland                                                      1
dianella wa                                                    1
62 blamey street,  kelvin grove qld 4059                       1
64 hoa hong,  cau kieu ward                                    1
45 tran huy lieu street,  ward 12,  phu nhuan dist             1
144/48 phan van han street,  ward 17,  binh thanh district     1
38 wharf st,  brisbane city                                    1
123 nguyen trai street,  hanoi                                 1
boston,  massachusetts                                         1
adelaide,  sa                                                  1
nguyen binh khiem street,  saigon ward                         1
ninh thuan                                                     1
thu duc                                                        1
hcmc                                                           1
12b đường số 406 phước long a,  quận 9                         1
hà nội                                                         1
Name: count, dtype: int64

In [51]:
conditions_city = [
    # Ho Chi Minh City variations
    dim_customer['city'].str.contains(
        'ho chi minh|hochiminh|hcm|district|thu duc|go vap|binh thanh|tan binh|phu nhuan|quan|tphcm|tp.hcm|saigon',
        case=False, na=False
    ),
    # Hanoi variations
    dim_customer['city'].str.contains(
        'hanoi|ha noi|hà nội|bac|gia lam|dong da|cau giay|hoan kiem',
        case=False, na=False
    ),
    # Other Vietnam cities
    dim_customer['city'].str.contains(
        'da nang|danang|hue|can tho|vung tau|nha trang|vinh|hai phong',
        case=False, na=False
    ),
    # Sydney
    dim_customer['city'].str.contains(
        'sydney|nsw|bankstown|asquith|parramatta|chatswood|blacktown',
        case=False, na=False
    ),
    # Melbourne
    dim_customer['city'].str.contains(
        'melbourne|vic|richmond|fitzroy|collingwood|brunswick',
        case=False, na=False
    ),
    # Other Australian cities
    dim_customer['city'].str.contains(
        'brisbane|perth|adelaide|canberra|darwin|hobart|qld|wa|sa',
        case=False, na=False
    ),
    # US cities
    dim_customer['city'].str.contains(
        'san francisco|phoenix|new york|los angeles|chicago|houston|dallas|austin|seattle',
        case=False, na=False
    ),
    # US states
    dim_customer['city'].str.strip().str.lower().isin([
        'ca', 'az', 'oh', 'tx', 'ny', 'wa', 'fl'
    ]),
    # Saudi Arabia
    dim_customer['city'].str.contains(
        'riyadh|jeddah|mecca|medina|saudi',
        case=False, na=False
    ),
]

choices_city = [
    'Ho Chi Minh City',
    'Hanoi',
    'Other Vietnam',
    'Sydney',
    'Melbourne',
    'Other Australia',
    'Other United States',
    'Other United States',
    'Saudi Arabia',
]

In [52]:
dim_customer['clean_city'] = np.select(conditions_city,choices_city,default='Unknown')
dim_customer['clean_city'].value_counts()

clean_city
Unknown                43
Ho Chi Minh City       39
Other Australia        14
Sydney                  6
Hanoi                   4
Melbourne               4
Other United States     2
Name: count, dtype: int64

We are moving to final columns from dim customer is education

In [74]:
# We pic kthe highest qualification for people

conditions_edu = [
    # PhD first — highest
    dim_customer['education'].str.contains('phd|doctorate', case=False, na=False),
    # Then Master
    dim_customer['education'].str.contains('master', case=False, na=False),
    # Then Bachelor
    dim_customer['education'].str.contains('bachelor', case=False, na=False),
    dim_customer['education'].str.contains('diploma', case=False, na=False),
    dim_customer['education'].str.contains('university', case=False, na=False),
    dim_customer['education'].str.contains('college', case=False, na=False),
    dim_customer['education'].str.contains('highschool', case=False, na=False),
]

choices_edu = ['PhD', 'Master', 'Bachelor', 'Diploma','University','College','Highschool']

dim_customer['education_level'] = np.select(
    conditions_edu,
    choices_edu,
    default='Unknown'
)

In [75]:
dim_customer['education_level'].value_counts()

education_level
University    40
Bachelor      34
Master        19
Diploma        9
Unknown        8
Highschool     1
College        1
Name: count, dtype: int64

In [76]:
dim_customer.columns

Index(['candidate_name', 'email', 'phone', 'location', 'education',
       'email_valid', 'customer_id', 'country', 'city', 'country_clean',
       'clean_city', 'education_level'],
      dtype='object')

In [82]:
final_dim_customer = dim_customer[['customer_id','candidate_name', 'email', 'phone','clean_city','country_clean','education_level']]\
.rename(columns={
        'clean_city':'city',
        'country_clean':'country',
        'education_level':'education'
})
final_dim_customer

,customer_id,candidate_name,email,phone,city,country,education
0,1,christopher davis,chris.davis.1990@email.com,4155550776,Other Australia,United States,Bachelor
1,2,minh vu,vddminh89@gmail.com,840904562633,Ho Chi Minh City,Vietnam,Bachelor
2,3,tran quoc bao,21bao.tq@vinuni.edu.vn,84382780002,Hanoi,Vietnam,Bachelor
3,4,le anh vy (chloe),chloe@theseedsoft.com,0404262401,Sydney,Australia,Diploma
4,5,amanda martinez,amanda.martinez@email.com,6025550811,Other United States,United States,Master
...,...,...,...,...,...,...,...
107,108,hoàng minh ngọc hải,hoangminhngochai@gmail.com,84916888143,Unknown,Vietnam,University
108,109,nguyễn ngọc bảo trân,nguyennogcbaotran.contact@gmail.com,84987934364,Ho Chi Minh City,Vietnam,University
109,110,abdul karim,abdul.karim00035@gmail.com,966555168042,Unknown,Saudi Arabia,Bachelor
110,111,phil dinh,phildinhdata@gmail.com,0451840818,Sydney,Australia,Master
111,112,tai nguyen,nguyenductaidhsp@gmail.com,84907959003,Ho Chi Minh City,Vietnam,Bachelor

In [83]:
final_dim_customer.to_csv('dim_user.csv',index=False)