In [1]:
import pandas as pd
import numpy as np
import json

In [2]:
df_main = pd.read_excel("MentorMe-CV-File-20260224.xlsx",sheet_name="Main_table")
df_user = pd.read_csv("dim_user.csv")

In [4]:
# Open main table to see the columns again
df_main.head()

,id,user_id,analysis_id,candidate_name,email,phone,status,file_name,created_at,updated_at,...,formatting_issues,sections.coreCompetencies,sections.leadershipManagement,sections.certifications,sections.languages,sections.passportVisaHistory,sections.military,sections.volunteer,sections.communityWork,additional_sections
0,2,NaN,1759998111377,Christopher Davis,chris.davis.1990@email.com,(415) 555-0776,craft,Christopher Davis_Flutter Developer.pdf,2025-10-09T08:22:24,2025-10-09T08:22:24,...,"[""Placeholder GitHub link text"",""LinkedIn URL ...",[],NaN,[],[],NaN,NaN,NaN,NaN,NaN
1,3,NaN,1759998769335,Minh Vu,vddminh89@gmail.com,(84) 090-4562633,craft,CV_Minh Vu - Minh Vu.pdf,2025-10-09T08:33:36,2025-10-09T08:33:36,...,"[""Hyphen and bullet mix inconsistent"",""No unif...","[""Problem solving"",""Leadership"",""ERP System Ev...",NaN,[],[],NaN,NaN,NaN,NaN,NaN
2,5,NaN,1759999340602,TRAN QUOC BAO,21bao.tq@vinuni.edu.vn,(+84) 382780002,craft,BaoTran_resume - BaÌo TraÌÌn.pdf,2025-10-09T08:42:56,2025-10-09T08:42:56,...,"[""Inconsistent date formats across entries"",""J...","[""Python"",""Matlab"",""TensorFlow"",""React.js"",""Fi...",NaN,"[""Deep Learning Specialization, DeepLearning.A...","[{""language"":""English"",""proficiency"":""Fluent""}]",NaN,NaN,NaN,NaN,NaN
3,11,NaN,1760001071242,Le Anh Vy (Chloe),chloe@theseedsoft.com,0404 262 401,craft,Le Anh Vy - CV.PDF,2025-10-09T09:12:00,2025-10-09T09:12:00,...,"[""Bullet styles vary"",""Overseas roles merged b...",[],NaN,"[""LinkedIN Project Management Certification""]",[],NaN,NaN,NaN,NaN,NaN
4,14,NaN,1760001127938,Le Anh Vy (Chloe),chloe@theseedsoft.com,0404 262 401,craft,Le Anh Vy - CV.PDF,2025-10-09T09:13:11,2025-10-09T09:13:11,...,"[""Inconsistent date format styles"",""Bullet sty...","[""Program Management"",""Project Management"",""Co...",NaN,"[""LinkedIN Project Management Certification | ...",[],NaN,NaN,NaN,NaN,NaN

In [5]:
# Open dim customer to see the columns again
df_user.head()

,customer_id,candidate_name,email,phone,city,country,education
0,1,christopher davis,chris.davis.1990@email.com,4155550776,Other Australia,United States,Bachelor
1,2,minh vu,vddminh89@gmail.com,840904562633,Ho Chi Minh City,Vietnam,Bachelor
2,3,tran quoc bao,21bao.tq@vinuni.edu.vn,84382780002,Hanoi,Vietnam,Bachelor
3,4,le anh vy (chloe),chloe@theseedsoft.com,0404262401,Sydney,Australia,Diploma
4,5,amanda martinez,amanda.martinez@email.com,6025550811,Other United States,United States,Master

In [8]:
# How many nulls in each potential join column in df_main?
print(df_main[['candidate_name', 'email']].isnull().sum())

# How many nulls in dim_customer join columns?
print(df_user[['candidate_name', 'email']].isnull().sum())

candidate_name     9
email             17
dtype: int64
candidate_name    2
email             6
dtype: int64

We need to join both table to get normalize customer_id continuing to generate different table for analysis

In [9]:
# Normalize candidate name and email from main table
df_main['candidate_name'] = df_main['candidate_name'].str.lower().str.strip()
df_main['email'] = df_main['email'].str.lower().str.strip()

In [11]:
# We try to join 2 tables first then continue the work
df_merge = df_main.merge(df_user[['customer_id','candidate_name','email']],
                         on=['candidate_name','email'],
                         how='left')
df_merge.head()

,id,user_id,analysis_id,candidate_name,email,phone,status,file_name,created_at,updated_at,...,sections.coreCompetencies,sections.leadershipManagement,sections.certifications,sections.languages,sections.passportVisaHistory,sections.military,sections.volunteer,sections.communityWork,additional_sections,customer_id
0,2,NaN,1759998111377,christopher davis,chris.davis.1990@email.com,(415) 555-0776,craft,Christopher Davis_Flutter Developer.pdf,2025-10-09T08:22:24,2025-10-09T08:22:24,...,[],NaN,[],[],NaN,NaN,NaN,NaN,NaN,1
1,3,NaN,1759998769335,minh vu,vddminh89@gmail.com,(84) 090-4562633,craft,CV_Minh Vu - Minh Vu.pdf,2025-10-09T08:33:36,2025-10-09T08:33:36,...,"[""Problem solving"",""Leadership"",""ERP System Ev...",NaN,[],[],NaN,NaN,NaN,NaN,NaN,2
2,5,NaN,1759999340602,tran quoc bao,21bao.tq@vinuni.edu.vn,(+84) 382780002,craft,BaoTran_resume - BaÌo TraÌÌn.pdf,2025-10-09T08:42:56,2025-10-09T08:42:56,...,"[""Python"",""Matlab"",""TensorFlow"",""React.js"",""Fi...",NaN,"[""Deep Learning Specialization, DeepLearning.A...","[{""language"":""English"",""proficiency"":""Fluent""}]",NaN,NaN,NaN,NaN,NaN,3
3,11,NaN,1760001071242,le anh vy (chloe),chloe@theseedsoft.com,0404 262 401,craft,Le Anh Vy - CV.PDF,2025-10-09T09:12:00,2025-10-09T09:12:00,...,[],NaN,"[""LinkedIN Project Management Certification""]",[],NaN,NaN,NaN,NaN,NaN,4
4,14,NaN,1760001127938,le anh vy (chloe),chloe@theseedsoft.com,0404 262 401,craft,Le Anh Vy - CV.PDF,2025-10-09T09:13:11,2025-10-09T09:13:11,...,"[""Program Management"",""Project Management"",""Co...",NaN,"[""LinkedIN Project Management Certification | ...",[],NaN,NaN,NaN,NaN,NaN,4

In [12]:
# Check null value for id after merging
df_merge['customer_id'].isnull().sum()

np.int64(0)

In [14]:
# Show rows where email is null — did they get a customer_id?
df_merge[df_merge['email'].isnull()][['candidate_name', 'email', 'customer_id']]

         candidate_name email  customer_id
13      richard sanchez   NaN           12
14      richard sanchez   NaN           12
18   hồ thị phương dung   NaN           15
44                  NaN   NaN           28
45                  NaN   NaN           28
46                  NaN   NaN           28
100     richard sanchez   NaN           12
120              lam le   NaN           80
126         bui duy bao   NaN           86
137     tran tuyet ngoc   NaN           90
151                 NaN   NaN           28
152                 NaN   NaN           28
153                 NaN   NaN           28
154                 NaN   NaN           28
167                 NaN   NaN           28
176     tran tuyet ngoc   NaN           90
182     tran tuyet ngoc   NaN           90

In [16]:
# For customer no email we can see put the customer_id = 28
df_merge[df_merge['customer_id']==28]

,id,user_id,analysis_id,candidate_name,email,phone,status,file_name,created_at,updated_at,...,sections.coreCompetencies,sections.leadershipManagement,sections.certifications,sections.languages,sections.passportVisaHistory,sections.military,sections.volunteer,sections.communityWork,additional_sections,customer_id
44,102,NaN,1760606024960,NaN,NaN,NaN,craft,developer_cv_sample.pdf,2025-10-16T09:13:51,2025-10-16T09:13:51,...,[],NaN,[],[],NaN,NaN,NaN,NaN,[],28
45,103,NaN,1760606182631,NaN,NaN,NaN,craft,test_resume.pdf,2025-10-16T09:16:27,2025-10-16T09:16:27,...,[],NaN,[],[],NaN,NaN,NaN,NaN,[],28
46,104,NaN,1760606190301,NaN,NaN,NaN,craft,test-cv.pdf,2025-10-16T09:16:37,2025-10-16T09:16:37,...,[],NaN,[],[],NaN,NaN,NaN,NaN,[],28
151,282,NaN,1766970122432,NaN,NaN,NaN,craft,QC_1.pdf,2025-12-29T01:02:34,2025-12-29T01:02:34,...,"[""Test Automation"",""Functional Testing"",""Regre...",NaN,[],[],NaN,NaN,NaN,NaN,[],28
152,283,NaN,1766970472090,NaN,NaN,NaN,craft,QC_1.pdf,2025-12-29T01:08:22,2025-12-29T01:08:22,...,"[""Test Automation"",""Manual Testing"",""API Testi...",NaN,[],[],NaN,NaN,NaN,NaN,[],28
153,284,NaN,1766970531512,NaN,NaN,NaN,craft,QC_1.pdf,2025-12-29T01:09:24,2025-12-29T01:09:24,...,"[""Python"",""JavaScript"",""Test Automation"",""CI/C...",NaN,[],[],NaN,NaN,NaN,NaN,[],28
154,285,112.0,1766970593003,NaN,NaN,NaN,craft,QC_1.pdf,2025-12-29T01:10:17,2025-12-29T01:10:17,...,"[""Python"",""Javascript"",""Typescript"",""Java"",""OO...",NaN,[],[],NaN,NaN,NaN,NaN,[],28
167,321,NaN,1768228269914,NaN,NaN,NaN,craft,Empty CV.docx,2026-01-12T14:31:16,2026-01-12T14:31:16,...,[],NaN,[],[],NaN,NaN,NaN,NaN,[],28

In [18]:
# now we check our dataset with customer_id
df_merge.head(3).T

,0,1,2
id,2,3,5
user_id,NaN,NaN,NaN
analysis_id,1759998111377,1759998769335,1759999340602
candidate_name,christopher davis,minh vu,tran quoc bao
email,chris.davis.1990@email.com,vddminh89@gmail.com,21bao.tq@vinuni.edu.vn
phone,(415) 555-0776,(84) 090-4562633,(+84) 382780002
status,craft,craft,craft
file_name,Christopher Davis_Flutter Developer.pdf,CV_Minh Vu - Minh Vu.pdf,BaoTran_resume - BaÌo TraÌÌn.pdf
created_at,2025-10-09T08:22:24,2025-10-09T08:33:36,2025-10-09T08:42:56
updated_at,2025-10-09T08:22:24,2025-10-09T08:33:36,2025-10-09T08:42:56
overview,Proficient Flutter Developer with 2 years buil...,Seasoned System Manager with 9 years of ERP an...,Electrical Engineering student with research e...
technical_skills,"[{""name"":""Flutter"",""level"":""Advanced"",""score"":...","[{""name"":""ERP System Evaluation"",""level"":""Adva...","[{""name"":""Python"",""level"":""Advanced"",""score"":8..."
soft_skills,"[{""name"":""Collaboration"",""level"":""Intermediate...","[{""name"":""Problem solving"",""level"":""Expert"",""s...",[]
strengths,"[""Proficient Flutter & Dart development"",""Cros...","[""ERP systems implementation with Odoo"",""BI re...","[""Expertise in robust EV charging optimization..."
gaps,"[""Generic project description"",""Missing GitHub...","[""Missing professional summary section"",""Lacks...","[""No professional summary or objective stateme..."
keywords,"[""Flutter"",""Dart"",""Firebase"",""RESTful APIs"",""A...","[""ERP"",""Odoo"",""SQL"",""Power BI"",""BI reporting"",...","[""Python"",""Matlab"",""TensorFlow"",""Deep Learning..."
experience_level.level,Mid level,Senior level,Entry level
experience_level.years,2,9,3
recommendations,"[""Add actual GitHub project links"",""Quantify a...","[""Add a professional summary highlighting key ...","[""Add a professional summary highlighting AI/M..."
regional_insights,"[""Australian employers expect local phone form...","[""Use Australian English spelling (e.g., \""opt...","[""Clearly state Australian work rights or visa..."
location,"San Francisco, CA","Hochiminh city, Vietnam","Da Ton, Gia Lam, Hanoi, Vietnam"
job_role,Flutter development,Data analytics,Artificial intelligence
education,"[""Bachelor of Engineering in Computer Engineer...","[""2022 – 2025 Advanced Diploma in Software Eng...","[""VinUniversity, Gia Lam, Hanoi – Bachelor of ..."
work_history,"[""Flutter Developer\nAppMakers Co., London, UK...","[""System Manager\nJYSK Vietnam – Furniture ret...","[""Research Assistant\nCollege of Engineering a..."
formatting_issues,"[""Placeholder GitHub link text"",""LinkedIn URL ...","[""Hyphen and bullet mix inconsistent"",""No unif...","[""Inconsistent date formats across entries"",""J..."
sections.coreCompetencies,[],"[""Problem solving"",""Leadership"",""ERP System Ev...","[""Python"",""Matlab"",""TensorFlow"",""React.js"",""Fi..."
sections.leadershipManagement,NaN,NaN,NaN
sections.certifications,[],[],"[""Deep Learning Specialization, DeepLearning.A..."
sections.languages,[],[],"[{""language"":""English"",""proficiency"":""Fluent""}]"
sections.passportVisaHistory,NaN,NaN,NaN
sections.military,NaN,NaN,NaN
sections.volunteer,NaN,NaN,NaN
sections.communityWork,NaN,NaN,NaN
additional_sections,NaN,NaN,NaN
customer_id,1,2,3

In [20]:
# We extract to skills table then work from here
df_skill = df_merge[['customer_id','analysis_id','technical_skills','soft_skills']].copy()
df_skill

,customer_id,analysis_id,technical_skills,soft_skills
0,1,1759998111377,"[{""name"":""Flutter"",""level"":""Advanced"",""score"":...","[{""name"":""Collaboration"",""level"":""Intermediate..."
1,2,1759998769335,"[{""name"":""ERP System Evaluation"",""level"":""Adva...","[{""name"":""Problem solving"",""level"":""Expert"",""s..."
2,3,1759999340602,"[{""name"":""Python"",""level"":""Advanced"",""score"":8...",[]
3,4,1760001071242,"[{""name"":""Microsoft Office (Excel, Word, Power...","[{""name"":""Project Management"",""level"":""Expert""..."
4,4,1760001127938,"[{""name"":""Microsoft Office: Excel, Word, Power...","[{""name"":""Project Management"",""level"":""Expert""..."
...,...,...,...,...
186,100,1770000367449,"[{""name"":""Manual Testing"",""level"":""Expert""},{""...","[{""name"":""Team Collaboration"",""level"":""Advance..."
187,110,1770480528604,"[{""name"":""CMMS (Engica)"",""level"":""Expert""},{""n...","[{""name"":""Leadership"",""level"":""Expert""},{""name..."
188,111,1770645524167,"[{""name"":""Python"",""level"":""Advanced""},{""name"":...","[{""name"":""Problem Solving"",""level"":""Advanced""}..."
189,111,1770645573729,"[{""name"":""Python"",""level"":""Intermediate""},{""na...","[{""name"":""Data-Driven & Customer Success Focus..."
190,112,1771904249832,"[{""name"":""C# / .NET"",""level"":""Expert""},{""name""...","[{""name"":""Team leadership & mentoring"",""level""..."

In [22]:
# Before we dive in we will check the value from technical and sofk skills
print("We check first row for tech skills and data type")
print(df_skill['technical_skills'].iloc[0])
print(type(df_skill['technical_skills'].iloc[0]))
print("\n")

print("We check first row for soft skills and data type")
print(df_skill['soft_skills'].iloc[0])
print(type(df_skill['soft_skills'].iloc[0]))
print("\n")

We check first row for tech skills and data type
[{"name":"Flutter","level":"Advanced","score":85},{"name":"Dart","level":"Advanced","score":80},{"name":"Swift","level":"Intermediate","score":60},{"name":"Kotlin","level":"Intermediate","score":60},{"name":"Provider","level":"Intermediate","score":65},{"name":"BLoC","level":"Intermediate","score":65},{"name":"Riverpod","level":"Intermediate","score":65},{"name":"Android Studio","level":"Intermediate","score":70},{"name":"VS Code","level":"Intermediate","score":70},{"name":"Xcode","level":"Intermediate","score":65},{"name":"Git","level":"Advanced","score":75},{"name":"Firebase","level":"Intermediate","score":70},{"name":"SQLite","level":"Intermediate","score":60},{"name":"RESTful APIs","level":"Intermediate","score":70},{"name":"JSON","level":"Intermediate","score":70},{"name":"Agile/Scrum","level":"Intermediate","score":65}]
<class 'str'>


We check first row for soft skills and data type
[{"name":"Collaboration","level":"Intermediate","score":70},{"name":"Problem-solving","level":"Intermediate","score":70}]
<class 'str'>

In [24]:
# We can understand right now data type is str and data structure for skill columns are list of dictionaries
# We will use small row to work with, if it work will apply to the rest of them
raw = df_skill['technical_skills'].iloc[0]
parsed = json.loads(raw)

print(type(parsed))
print(parsed[1])

<class 'list'>
{'name': 'Dart', 'level': 'Advanced', 'score': 80}

In [25]:
df_test = pd.DataFrame(parsed)
df_test

              name         level  score
0          Flutter      Advanced     85
1             Dart      Advanced     80
2            Swift  Intermediate     60
3           Kotlin  Intermediate     60
4         Provider  Intermediate     65
5             BLoC  Intermediate     65
6         Riverpod  Intermediate     65
7   Android Studio  Intermediate     70
8          VS Code  Intermediate     70
9            Xcode  Intermediate     65
10             Git      Advanced     75
11        Firebase  Intermediate     70
12          SQLite  Intermediate     60
13    RESTful APIs  Intermediate     70
14            JSON  Intermediate     70
15     Agile/Scrum  Intermediate     65

In [37]:
results = []

for index,row in df_skill.iterrows():
    # Step 1: parse the json string
    parsed = json.loads(row['technical_skills'])

    # step 2: convert to dataframe
    temp_df = pd.DataFrame(parsed)

    #Step 3: add customer_id and analysis_id to everyrow
    temp_df['customer_id'] = row['customer_id']
    temp_df['analysis_id'] = row['analysis_id']
    temp_df['skill_type'] = 'technical_skills'
    results.append(temp_df)

    # step 4: Append the result
    df_tech = pd.concat(results).reset_index(drop=True)
    print(df_tech)
    print(type(df_tech))

              name         level  score  customer_id    analysis_id  \
0          Flutter      Advanced     85            1  1759998111377
1             Dart      Advanced     80            1  1759998111377
2            Swift  Intermediate     60            1  1759998111377
3           Kotlin  Intermediate     60            1  1759998111377
4         Provider  Intermediate     65            1  1759998111377
5             BLoC  Intermediate     65            1  1759998111377
6         Riverpod  Intermediate     65            1  1759998111377
7   Android Studio  Intermediate     70            1  1759998111377
8          VS Code  Intermediate     70            1  1759998111377
9            Xcode  Intermediate     65            1  1759998111377
10             Git      Advanced     75            1  1759998111377
11        Firebase  Intermediate     70            1  1759998111377
12          SQLite  Intermediate     60            1  1759998111377
13    RESTful APIs  Intermediate     70            1  1759998111377
14            JSON  Intermediate     70            1  1759998111377
15     Agile/Scrum  Intermediate     65            1  1759998111377

          skill_type
0   technical_skills
1   technical_skills
2   technical_skills
3   technical_skills
4   technical_skills
5   technical_skills
6   technical_skills
7   technical_skills
8   technical_skills
9   technical_skills
10  technical_skills
11  technical_skills
12  technical_skills
13  technical_skills
14  technical_skills
15  technical_skills
<class 'pandas.core.frame.DataFrame'>
                     name         level  score  customer_id    analysis_id  \
0                 Flutter      Advanced     85            1  1759998111377
1                    Dart      Advanced     80            1  1759998111377
2                   Swift  Intermediate     60            1  1759998111377
3                  Kotlin  Intermediate     60            1  1759998111377
4                Provider  Intermediate     65            1  1759998111377
5                    BLoC  Intermediate     65            1  1759998111377
6                Riverpod  Intermediate     65            1  1759998111377
7          Android Studio  Intermediate     70            1  1759998111377
8                 VS Code  Intermediate     70            1  1759998111377
9                   Xcode  Intermediate     65            1  1759998111377
10                    Git      Advanced     75            1  1759998111377
11               Firebase  Intermediate     70            1  1759998111377
12                 SQLite  Intermediate     60            1  1759998111377
13           RESTful APIs  Intermediate     70            1  1759998111377
14                   JSON  Intermediate     70            1  1759998111377
15            Agile/Scrum  Intermediate     65            1  1759998111377
16  ERP System Evaluation      Advanced     85            2  1759998769335
17                    SQL      Advanced     80            2  1759998769335
18               Power BI      Advanced     85            2  1759998769335
19                   Odoo      Advanced     88            2  1759998769335
20          Data Analysis      Advanced     90            2  1759998769335
21               HTML/CSS  Intermediate     70            2  1759998769335
22             Javascript  Intermediate     65            2  1759998769335
23                 Python  Intermediate     60            2  1759998769335

          skill_type
0   technical_skills
1   technical_skills
2   technical_skills
3   technical_skills
4   technical_skills
5   technical_skills
6   technical_skills
7   technical_skills
8   technical_skills
9   technical_skills
10  technical_skills
11  technical_skills
12  technical_skills
13  technical_skills
14  technical_skills
15  technical_skills
16  technical_skills
17  technical_skills
18  technical_skills
19  technical_skills
20  technical_skills
21  technical_skills
22  technical_skills
23  technical_skills
<class 'pandas.core.frame.DataFrame'>
                     name         level  score  customer_id    analysis_id  \
0                 Flutter      Advanced     85            1  1759998111377
1                    Dart      Advanced     80            1  1759998111377
2                   Swift  Intermediate     60            1  1759998111377
3                  Kotlin  Intermediate     60            1  1759998111377
4                Provider  Intermediate     65            1  1759998111377
5                    BLoC  Intermediate     65            1  1759998111377
6                Riverpod  Intermediate     65            1  1759998111377
7          Android Studio  Intermediate     70            1  1759998111377
8                 VS Code  Intermediate     70            1  1759998111377
9                   Xcode  Intermediate     65            1  1759998111377
10                    Git      Advanced     75            1  1759998111377
11               Firebase  Intermediate     70            1  1759998111377
12                 SQLite  Intermediate     60            1  1759998111377
13           RESTful APIs  Intermediate     70            1  1759998111377
14                   JSON  Intermediate     70            1  1759998111377
15            Agile/Scrum  Intermediate     65            1  1759998111377
16  ERP System Evaluation      Advanced     85            2  1759998769335
17                    SQL      Advanced     80            2  1759998769335
18               Power BI      Advanced     85            2  1759998769335
19                   Odoo      Advanced     88            2  1759998769335
20          Data Analysis      Advanced     90            2  1759998769335
21               HTML/CSS  Intermediate     70            2  1759998769335
22             Javascript  Intermediate     65            2  1759998769335
23                 Python  Intermediate     60            2  1759998769335
24                 Python      Advanced     85            3  1759999340602
25                 Matlab      Advanced     80            3  1759999340602
26                  Numpy  Intermediate     75            3  1759999340602
27                 Pandas  Intermediate     75            3  1759999340602
28             TensorFlow  Intermediate     70            3  1759999340602
29                  Figma  Intermediate     70            3  1759999340602
30               React.js  Intermediate     70            3  1759999340602
31         Linux (Ubuntu)  Intermediate     65            3  1759999340602

          skill_type
0   technical_skills
1   technical_skills
2   technical_skills
3   technical_skills
4   technical_skills
5   technical_skills
6   technical_skills
7   technical_skills
8   technical_skills
9   technical_skills
10  technical_skills
11  technical_skills
12  technical_skills
13  technical_skills
14  technical_skills
15  technical_skills
16  technical_skills
17  technical_skills
18  technical_skills
19  technical_skills
20  technical_skills
21  technical_skills
22  technical_skills
23  technical_skills
24  technical_skills
25  technical_skills
26  technical_skills
27  technical_skills
28  technical_skills
29  technical_skills
30  technical_skills
31  technical_skills
<class 'pandas.core.frame.DataFrame'>
                                                 name         level  score  \
0                                             Flutter      Advanced     85
1                                                Dart      Advanced     80
2                                               Swift  Intermediate     60
3                                              Kotlin  Intermediate     60
4                                            Provider  Intermediate     65
5                                                BLoC  Intermediate     65
6                                            Riverpod  Intermediate     65
7                                      Android Studio  Intermediate     70
8                                             VS Code  Intermediate     70
9                                               Xcode  Intermediate     65
10                                                Git      Advanced     75
11                                           Firebase  Intermediate     70
12                                             SQLite  Intermediate     60
13                                       RESTful APIs  Intermediate     70
14                                               JSON  Intermediate     70
15                                        Agile/Scrum  Intermediate     65
16                              ERP System Evaluation      Advanced     85
17                                                SQL      Advanced     80
18                                           Power BI      Advanced     85
19                                               Odoo      Advanced     88
20                                      Data Analysis      Advanced     90
21                                           HTML/CSS  Intermediate     70
22                                         Javascript  Intermediate     65
23                                             Python  Intermediate     60
24                                             Python      Advanced     85
25                                             Matlab      Advanced     80
26                                              Numpy  Intermediate     75
27                                             Pandas  Intermediate     75
28                                         TensorFlow  Intermediate     70
29                                              Figma  Intermediate     70
30                                           React.js  Intermediate     70
31                                     Linux (Ubuntu)  Intermediate     65
32         Microsoft Office (Excel, Word, PowerPoint)      Advanced     85
33  Agile Project Management tools (Monday, Trello...  Intermediate     75
34                    Design & Clip Creation software  Intermediate     70
35                             No-Code App: Glide App      Beginner     60

    customer_id    analysis_id        skill_type
0             1  1759998111377  technical_skills
1             1  1759998111377  technical_skills
2             1  1759998111377  technical_skills
3             1  1759998111377  technical_skills
4             1  1759998111377  technical_skills
5             1  1759998111377  technical_skills
6             1  1759998111377  technical_skills
7             1  1759998111377  technical_skills
8             1  1759998111377  technical_skills
9             1  1759998111377  technical_skills
10            1  1759998111377  technical_skills
11            1  1759998111377  technical_skills
12            1  1759998111377  technical_skills
13            1  1759998111377  technical_skills
14            1  1759998111377  technical_skills
15            1  1759998111377  technical_skills
16            2  1759998769335  technical_skills
17            2  1759998769335  technical_skills
18            2  1759998769335  technical_skills
19            2  1759998769335  technical_skills
20            2  1759998769335  technical_skills
21            2  1759998769335  technical_skills
22            2  1759998769335  technical_skills
23            2  1759998769335  technical_skills
24            3  1759999340602  technical_skills
25            3  1759999340602  technical_skills
26            3  1759999340602  technical_skills
27            3  1759999340602  technical_skills
28            3  1759999340602  technical_skills
29            3  1759999340602  technical_skills
30            3  1759999340602  technical_skills
31            3  1759999340602  technical_skills
32            4  1760001071242  technical_skills
33            4  1760001071242  technical_skills
34            4  1760001071242  technical_skills
35            4  1760001071242  technical_skills
<class 'pandas.core.frame.DataFrame'>
                                                 name         level  score  \
0                                             Flutter      Advanced     85
1                                                Dart      Advanced     80
2                                               Swift  Intermediate     60
3                                              Kotlin  Intermediate     60
4                                            Provider  Intermediate     65
5                                                BLoC  Intermediate     65
6                                            Riverpod  Intermediate     65
7                                      Android Studio  Intermediate     70
8                                             VS Code  Intermediate     70
9                                               Xcode  Intermediate     65
10                                                Git      Advanced     75
11                                           Firebase  Intermediate     70
12                                             SQLite  Intermediate     60
13                                       RESTful APIs  Intermediate     70
14                                               JSON  Intermediate     70
15                                        Agile/Scrum  Intermediate     65
16                              ERP System Evaluation      Advanced     85
17                                                SQL      Advanced     80
18                                           Power BI      Advanced     85
19                                               Odoo      Advanced     88
20                                      Data Analysis      Advanced     90
21                                           HTML/CSS  Intermediate     70
22                                         Javascript  Intermediate     65
23                                             Python  Intermediate     60
24                                             Python      Advanced     85
25                                             Matlab      Advanced     80
26                                              Numpy  Intermediate     75
27                                             Pandas  Intermediate     75
28                                         TensorFlow  Intermediate     70
29                                              Figma  Intermediate     70
30                                           React.js  Intermediate     70
31                                     Linux (Ubuntu)  Intermediate     65
32         Microsoft Office (Excel, Word, PowerPoint)      Advanced     85
33  Agile Project Management tools (Monday, Trello...  Intermediate     75
34                    Design & Clip Creation software  Intermediate     70
35                             No-Code App: Glide App      Beginner     60
36          Microsoft Office: Excel, Word, PowerPoint      Advanced     80
37  Agile Project Management tools: Monday, Trello...  Intermediate     70
38                  Design and Clip Creation software      Beginner     50
39                             No Code App: Glide App      Beginner     50

    customer_id    analysis_id        skill_type
0             1  1759998111377  technical_skills
1             1  1759998111377  technical_skills
2             1  1759998111377  technical_skills
3             1  1759998111377  technical_skills
4             1  1759998111377  technical_skills
5             1  1759998111377  technical_skills
6             1  1759998111377  technical_skills
7             1  1759998111377  technical_skills
8             1  1759998111377  technical_skills
9             1  1759998111377  technical_skills
10            1  1759998111377  technical_skills
11            1  1759998111377  technical_skills
12            1  1759998111377  technical_skills
13            1  1759998111377  technical_skills
14            1  1759998111377  technical_skills
15            1  1759998111377  technical_skills
16            2  1759998769335  technical_skills
17            2  1759998769335  technical_skills
18            2  1759998769335  technical_skills
19            2  1759998769335  technical_skills
20            2  1759998769335  technical_skills
21            2  1759998769335  technical_skills
22            2  1759998769335  technical_skills
23            2  1759998769335  technical_skills
24            3  1759999340602  technical_skills
25            3  1759999340602  technical_skills
26            3  1759999340602  technical_skills
27            3  1759999340602  technical_skills
28            3  1759999340602  technical_skills
29            3  1759999340602  technical_skills
30            3  1759999340602  technical_skills
31            3  1759999340602  technical_skills
32            4  1760001071242  technical_skills
33            4  1760001071242  technical_skills
34            4  1760001071242  technical_skills
35            4  1760001071242  technical_skills
36            4  1760001127938  technical_skills
37            4  1760001127938  technical_skills
38            4  1760001127938  technical_skills
39            4  1760001127938  technical_skills
<class 'pandas.core.frame.DataFrame'>
         name         level  score  customer_id    analysis_id  \
0     Flutter      Advanced     85            1  1759998111377
1        Dart      Advanced     80            1  1759998111377
2       Swift  Intermediate     60            1  1759998111377
3      Kotlin  Intermediate     60            1  1759998111377
4    Provider  Intermediate     65            1  1759998111377
..        ...           ...    ...          ...            ...
57    MongoDB  Intermediate     70            5  1760001497602
58  Cassandra  Intermediate     70            5  1760001497602
59     Docker  Intermediate     75            5  1760001497602
60        Git      Advanced     80            5  1760001497602
61    Jenkins  Intermediate     75            5  1760001497602

          skill_type
0   technical_skills
1   technical_skills
2   technical_skills
3   technical_skills
4   technical_skills
..               ...
57  technical_skills
58  technical_skills
59  technical_skills
60  technical_skills
61  technical_skills

[62 rows x 6 columns]
<class 'pandas.core.frame.DataFrame'>
                                 name         level  score  customer_id  \
0                             Flutter      Advanced     85            1
1                                Dart      Advanced     80            1
2                               Swift  Intermediate     60            1
3                              Kotlin  Intermediate     60            1
4                            Provider  Intermediate     65            1
..                                ...           ...    ...          ...
69      Webex Administration & Bomgar  Intermediate     65            6
70        Windows Desktop Environment        Expert     90            6
71    Active Directory Administration      Advanced     85            6
72              SCCM/MECM deployments      Advanced     80            6
73  ITSM Ticketing Tools (Freshworks)  Intermediate     70            6

      analysis_id        skill_type
0   1759998111377  technical_skills
1   1759998111377  technical_skills
2   1759998111377  technical_skills
3   1759998111377  technical_skills
4   1759998111377  technical_skills
..            ...               ...
69  1760001471313  technical_skills
70  1760001471313  technical_skills
71  1760001471313  technical_skills
72  1760001471313  technical_skills
73  1760001471313  technical_skills

[74 rows x 6 columns]
<class 'pandas.core.frame.DataFrame'>
              name         level  score  customer_id    analysis_id  \
0          Flutter      Advanced     85            1  1759998111377
1             Dart      Advanced     80            1  1759998111377
2            Swift  Intermediate     60            1  1759998111377
3           Kotlin  Intermediate     60            1  1759998111377
4         Provider  Intermediate     65            1  1759998111377
..             ...           ...    ...          ...            ...
77          Pandas  Intermediate     65            3  1760001555963

In [40]:
results_2 = []

for index,row in df_skill.iterrows():
    # Step 1: parse the json string
    parsed = json.loads(row['soft_skills'])

    # step 2: convert to dataframe
    temp_df = pd.DataFrame(parsed)

    #Step 3: add customer_id and analysis_id to everyrow
    temp_df['customer_id'] = row['customer_id']
    temp_df['analysis_id'] = row['analysis_id']
    temp_df['skill_type'] = 'soft_skills'
    results_2.append(temp_df)

    # step 4: Append the result
    df_soft = pd.concat(results_2).reset_index(drop=True)
    print(df_soft)
    print(type(df_soft))

              name         level  score  customer_id    analysis_id  \
0    Collaboration  Intermediate     70            1  1759998111377
1  Problem-solving  Intermediate     70            1  1759998111377

    skill_type
0  soft_skills
1  soft_skills
<class 'pandas.core.frame.DataFrame'>
                name         level  score  customer_id    analysis_id  \
0      Collaboration  Intermediate     70            1  1759998111377
1    Problem-solving  Intermediate     70            1  1759998111377
2    Problem solving        Expert     95            2  1759998769335
3         Leadership      Advanced     80            2  1759998769335
4  Business Analysis      Advanced     85            2  1759998769335

    skill_type
0  soft_skills
1  soft_skills
2  soft_skills
3  soft_skills
4  soft_skills
<class 'pandas.core.frame.DataFrame'>
                name         level  score  customer_id    analysis_id  \
0      Collaboration  Intermediate   70.0            1  1759998111377
1    Problem-solving  Intermediate   70.0            1  1759998111377
2    Problem solving        Expert   95.0            2  1759998769335
3         Leadership      Advanced   80.0            2  1759998769335
4  Business Analysis      Advanced   85.0            2  1759998769335

    skill_type
0  soft_skills
1  soft_skills
2  soft_skills
3  soft_skills
4  soft_skills
<class 'pandas.core.frame.DataFrame'>
                     name         level  score  customer_id    analysis_id  \
0           Collaboration  Intermediate   70.0            1  1759998111377
1         Problem-solving  Intermediate   70.0            1  1759998111377
2         Problem solving        Expert   95.0            2  1759998769335
3              Leadership      Advanced   80.0            2  1759998769335
4       Business Analysis      Advanced   85.0            2  1759998769335
5      Project Management        Expert   90.0            4  1760001071242
6  Stakeholder Management        Expert   88.0            4  1760001071242
7              Leadership        Expert   90.0            4  1760001071242
8             Negotiation      Advanced   80.0            4  1760001071242
9     Analytical Thinking      Advanced   80.0            4  1760001071242

    skill_type
0  soft_skills
1  soft_skills
2  soft_skills
3  soft_skills
4  soft_skills
5  soft_skills
6  soft_skills
7  soft_skills
8  soft_skills
9  soft_skills
<class 'pandas.core.frame.DataFrame'>
                         name         level  score  customer_id  \
0               Collaboration  Intermediate   70.0            1
1             Problem-solving  Intermediate   70.0            1
2             Problem solving        Expert   95.0            2
3                  Leadership      Advanced   80.0            2
4           Business Analysis      Advanced   85.0            2
5          Project Management        Expert   90.0            4
6      Stakeholder Management        Expert   88.0            4
7                  Leadership        Expert   90.0            4
8                 Negotiation      Advanced   80.0            4
9         Analytical Thinking      Advanced   80.0            4
10         Project Management        Expert   90.0            4
11       Contract Negotiation      Advanced   80.0            4
12            Team Leadership      Advanced   85.0            4
13  Stakeholder Communication      Advanced   85.0            4

      analysis_id   skill_type
0   1759998111377  soft_skills
1   1759998111377  soft_skills
2   1759998769335  soft_skills
3   1759998769335  soft_skills
4   1759998769335  soft_skills
5   1760001071242  soft_skills
6   1760001071242  soft_skills
7   1760001071242  soft_skills
8   1760001071242  soft_skills
9   1760001071242  soft_skills
10  1760001127938  soft_skills
11  1760001127938  soft_skills
12  1760001127938  soft_skills
13  1760001127938  soft_skills
<class 'pandas.core.frame.DataFrame'>
                         name         level  score  customer_id  \
0               Collaboration  Intermediate   70.0            1
1             Problem-solving  Intermediate   70.0            1
2             Problem solving        Expert   95.0            2
3                  Leadership      Advanced   80.0            2
4           Business Analysis      Advanced   85.0            2
5          Project Management        Expert   90.0            4
6      Stakeholder Management        Expert   88.0            4
7                  Leadership        Expert   90.0            4
8                 Negotiation      Advanced   80.0            4
9         Analytical Thinking      Advanced   80.0            4
10         Project Management        Expert   90.0            4
11       Contract Negotiation      Advanced   80.0            4
12            Team Leadership      Advanced   85.0            4
13  Stakeholder Communication      Advanced   85.0            4
14         Team Collaboration      Advanced   80.0            5
15              Communication  Intermediate   70.0            5

      analysis_id   skill_type
0   1759998111377  soft_skills
1   1759998111377  soft_skills
2   1759998769335  soft_skills
3   1759998769335  soft_skills
4   1759998769335  soft_skills
5   1760001071242  soft_skills
6   1760001071242  soft_skills
7   1760001071242  soft_skills
8   1760001071242  soft_skills
9   1760001071242  soft_skills
10  1760001127938  soft_skills
11  1760001127938  soft_skills
12  1760001127938  soft_skills
13  1760001127938  soft_skills
14  1760001497602  soft_skills
15  1760001497602  soft_skills
<class 'pandas.core.frame.DataFrame'>
                              name         level  score  customer_id  \
0                    Collaboration  Intermediate   70.0            1
1                  Problem-solving  Intermediate   70.0            1
2                  Problem solving        Expert   95.0            2
3                       Leadership      Advanced   80.0            2
4                Business Analysis      Advanced   85.0            2
5               Project Management        Expert   90.0            4
6           Stakeholder Management        Expert   88.0            4
7                       Leadership        Expert   90.0            4
8                      Negotiation      Advanced   80.0            4
9              Analytical Thinking      Advanced   80.0            4
10              Project Management        Expert   90.0            4
11            Contract Negotiation      Advanced   80.0            4
12                 Team Leadership      Advanced   85.0            4
13       Stakeholder Communication      Advanced   85.0            4
14              Team Collaboration      Advanced   80.0            5
15                   Communication  Intermediate   70.0            5
16  Written & verbal communication        Expert   90.0            6
17             Analytical thinking      Advanced   85.0            6
18                 Problem-solving      Advanced   85.0            6
19                Customer support      Advanced   85.0            6
20                   Documentation      Advanced   80.0            6

      analysis_id   skill_type
0   1759998111377  soft_skills
1   1759998111377  soft_skills
2   1759998769335  soft_skills
3   1759998769335  soft_skills
4   1759998769335  soft_skills
5   1760001071242  soft_skills
6   1760001071242  soft_skills
7   1760001071242  soft_skills
8   1760001071242  soft_skills
9   1760001071242  soft_skills
10  1760001127938  soft_skills
11  1760001127938  soft_skills
12  1760001127938  soft_skills
13  1760001127938  soft_skills
14  1760001497602  soft_skills
15  1760001497602  soft_skills
16  1760001471313  soft_skills
17  1760001471313  soft_skills
18  1760001471313  soft_skills
19  1760001471313  soft_skills
20  1760001471313  soft_skills
<class 'pandas.core.frame.DataFrame'>
                              name         level  score  customer_id  \
0                    Collaboration  Intermediate   70.0            1
1                  Problem-solving  Intermediate   70.0            1
2                  Problem solving        Expert   95.0            2
3                       Leadership      Advanced   80.0            2
4                Business Analysis      Advanced   85.0            2
5               Project Management        Expert   90.0            4
6           Stakeholder Management        Expert   88.0            4
7                       Leadership        Expert   90.0            4
8                      Negotiation      Advanced   80.0            4
9              Analytical Thinking      Advanced   80.0            4
10              Project Management        Expert   90.0            4
11            Contract Negotiation      Advanced   80.0            4
12                 Team Leadership      Advanced   85.0            4
13       Stakeholder Communication      Advanced   85.0            4
14              Team Collaboration      Advanced   80.0            5
15                   Communication  Intermediate   70.0            5
16  Written & verbal communication        Expert   90.0            6
17             Analytical thinking      Advanced   85.0            6
18                 Problem-solving      Advanced   85.0            6
19                Customer support      Advanced   85.0            6
20                   Documentation      Advanced   80.0            6
21                        Research  Intermediate   70.0            3
22                   Communication  Intermediate   65.0            3

      analysis_id   skill_type
0   1759998111377  soft_skills
1   1759998111377  soft_skills
2   1759998769335  soft_skills
3   1759998769335  soft_skills
4   1759998769335  soft_skills
5   1760001071242  soft_skills
6   1760001071242  soft_skills
7   1760001071242  soft_skills
8   1760001071242  soft_skills
9   1760001071242  soft_skills
10  1760001127938  soft_skills
11  1760001127938  soft_skills
12  1760001127938  soft_skills
13  1760001127938  soft_skills
14  1760001497602  soft_skills
15  1760001497602  soft_skills
16  1760001471313  soft_skills
17  1760001471313  soft_skills
18  1760001471313  soft_skills
19  1760001471313  soft_skills
20  1760001471313  soft_skills
21  1760001555963  soft_skills
22  1760001555963  soft_skills
<class 'pandas.core.frame.DataFrame'>
                              name         level  score  customer_id  \
0                    Collaboration  Intermediate   70.0            1
1                  Problem-solving  Intermediate   70.0            1
2                  Problem solving        Expert   95.0            2
3                       Leadership      Advanced   80.0            2
4                Business Analysis      Advanced   85.0            2
5               Project Management        Expert   90.0            4
6           Stakeholder Management        Expert   88.0            4
7                       Leadership        Expert   90.0            4
8                      Negotiation      Advanced   80.0            4
9              Analytical Thinking      Advanced   80.0            4
10              Project Management        Expert   90.0            4
11            Contract Negotiation      Advanced   80.0            4
12                 Team Leadership      Advanced   85.0            4
13       Stakeholder Communication      Advanced   85.0            4
14              Team Collaboration      Advanced   80.0            5
15                   Communication  Intermediate   70.0            5
16  Written & verbal communication        Expert   90.0            6
17             Analytical thinking      Advanced   85.0            6
18                 Problem-solving      Advanced   85.0            6
19                Customer support      Advanced   85.0            6
20                   Documentation      Advanced   80.0            6
21                        Research  Intermediate   70.0            3
22                   Communication  Intermediate   65.0            3
23                      Leadership      Advanced   85.0            7
24             Analytical Thinking      Advanced   85.0            7
25                   Communication      Advanced   85.0            7

      analysis_id   skill_type
0   1759998111377  soft_skills
1   1759998111377  soft_skills
2   1759998769335  soft_skills
3   1759998769335  soft_skills
4   1759998769335  soft_skills
5   1760001071242  soft_skills
6   1760001071242  soft_skills
7   1760001071242  soft_skills
8   1760001071242  soft_skills
9   1760001071242  soft_skills
10  1760001127938  soft_skills
11  1760001127938  soft_skills
12  1760001127938  soft_skills
13  1760001127938  soft_skills
14  1760001497602  soft_skills
15  1760001497602  soft_skills
16  1760001471313  soft_skills
17  1760001471313  soft_skills
18  1760001471313  soft_skills
19  1760001471313  soft_skills
20  1760001471313  soft_skills
21  1760001555963  soft_skills
22  1760001555963  soft_skills
23  1760002994028  soft_skills
24  1760002994028  soft_skills
25  1760002994028  soft_skills
<class 'pandas.core.frame.DataFrame'>
                              name         level  score  customer_id  \
0                    Collaboration  Intermediate   70.0            1
1                  Problem-solving  Intermediate   70.0            1
2                  Problem solving        Expert   95.0            2
3                       Leadership      Advanced   80.0            2
4                Business Analysis      Advanced   85.0            2
5               Project Management        Expert   90.0            4
6           Stakeholder Management        Expert   88.0            4
7                       Leadership        Expert   90.0            4
8                      Negotiation      Advanced   80.0            4
9              Analytical Thinking      Advanced   80.0            4
10              Project Management        Expert   90.0            4
11            Contract Negotiation      Advanced   80.0            4
12                 Team Leadership      Advanced   85.0            4
13       Stakeholder Communication      Advanced   85.0            4
14              Team Collaboration      Advanced   80.0            5
15                   Communication  Intermediate   70.0            5
16  Written & verbal communication        Expert   90.0            6
17             Analytical thinking      Advanced   85.0            6
18                 Problem-solving      Advanced   85.0            6
19                Customer support      Advanced   85.0            6
20                   Documentation      Advanced   80.0            6
21                        Research  Intermediate   70.0            3
22                   Communication  Intermediate   65.0            3
23                      Leadership      Advanced   85.0            7
24             Analytical Thinking      Advanced   85.0            7
25                   Communication      Advanced   85.0            7
26                      Leadership        Expert   90.0            8
27               Critical Thinking      Advanced   75.0            8
28                   Communication      Advanced   75.0            8
29                        Teamwork      Advanced   75.0            8

      analysis_id   skill_type
0   1759998111377  soft_skills
1   1759998111377  soft_skills
2   1759998769335  soft_skills
3   1759998769335  soft_skills
4   1759998769335  soft_skills
5   1760001071242  soft_skills
6   1760001071242  soft_skills
7   1760001071242  soft_skills
8   1760001071242  soft_skills
9   1760001071242  soft_skills
10  1760001127938  soft_skills
11  1760001127938  soft_skills
12  1760001127938  soft_skills
13  1760001127938  soft_skills
14  1760001497602  soft_skills
15  1760001497602  soft_skills
16  1760001471313  soft_skills
17  1760001471313  soft_skills
18  1760001471313  soft_skills
19  1760001471313  soft_skills
20  1760001471313  soft_skills
21  1760001555963  soft_skills
22  1760001555963  soft_skills
23  1760002994028  soft_skills
24  1760002994028  soft_skills
25  1760002994028  soft_skills
26  1760007201087  soft_skills
27  1760007201087  soft_skills
28  1760007201087  soft_skills
29  1760007201087  soft_skills
<class 'pandas.core.frame.DataFrame'>
                              name         level  score  customer_id  \
0                    Collaboration  Intermediate   70.0            1
1                  Problem-solving  Intermediate   70.0            1
2                  Problem solving        Expert   95.0            2
3                       Leadership      Advanced   80.0            2
4                Business Analysis      Advanced   85.0            2
5               Project Management        Expert   90.0            4
6           Stakeholder Management        Expert   88.0            4
7                       Leadership        Expert   90.0            4
8                      Negotiation      Advanced   80.0            4
9              Analytical Thinking      Advanced   80.0            4
10              Project Management        Expert   90.0            4
11            Contract Negotiation      Advanced   80.0            4
12                 Team Leadership      Advanced   85.0            4
13       Stakeholder Communication      Advanced   85.0            4
14              Team Collaboration      Advanced   80.0            5
15                   Communication  Intermediate   70.0            5
16  Written & verbal communication        Expert   90.0            6
17             Analytical thinking      Advanced   85.0            6
18                 Problem-solving      Advanced   85.0            6
19                Customer support      Advanced   85.0            6
20                   Documentation      Advanced   80.0            6
21                        Research  Intermediate   70.0            3
22                   Communication  Intermediate   65.0            3
23                      Leadership      Advanced   85.0            7
24             Analytical Thinking      Advanced   85.0            7
25                   Communication      Advanced   85.0            7
26                      Leadership        Expert   90.0            8
27               Critical Thinking      Advanced   75.0            8
28                   Communication      Advanced   75.0            8
29                        Teamwork      Advanced   75.0            8
30                      Leadership        Expert   95.0            9
31              Strategic Planning        Expert   90.0            9
32          Partnership Management      Advanced   85.0            9

      analysis_id   skill_type
0   1759998111377  soft_skills
1   1759998111377  soft_skills
2   1759998769335  soft_skills
3   1759998769335  soft_skills
4   1759998769335  soft_skills
5   1760001071242  soft_skills
6   1760001071242  soft_skills
7   1760001071242  soft_skills
8   1760001071242  soft_skills
9   1760001071242  soft_skills
10  1760001127938  soft_skills
11  1760001127938  soft_skills
12  1760001127938  soft_skills
13  1760001127938  soft_skills
14  1760001497602  soft_skills
15  1760001497602  soft_skills
16  1760001471313  soft_skills
17  1760001471313  soft_skills
18  1760001471313  soft_skills
19  1760001471313  soft_skills
20  1760001471313  soft_skills
21  1760001555963  soft_skills
22  1760001555963  soft_skills
23  1760002994028  soft_skills
24  1760002994028  soft_skills
25  1760002994028  soft_skills
26  1760007201087  soft_skills
27  1760007201087  soft_skills
28  1760007201087  soft_skills
29  1760007201087  soft_skills
30  1760007290148  soft_skills
31  1760007290148  soft_skills
32  1760007290148  soft_skills
<class 'pandas.core.frame.DataFrame'>
                              name         level  score  customer_id  \
0                    Collaboration  Intermediate   70.0            1
1                  Problem-solving  Intermediate   70.0            1
2                  Problem solving        Expert   95.0            2
3                       Leadership      Advanced   80.0            2
4                Business Analysis      Advanced   85.0            2

In [42]:
df_skills_final = pd.concat([df_soft,df_tech]).reset_index(drop=True)
df_skills_final

,name,level,score,customer_id,analysis_id,skill_type
0,Collaboration,Intermediate,70.0,1,1759998111377,soft_skills
1,Problem-solving,Intermediate,70.0,1,1759998111377,soft_skills
2,Problem solving,Expert,95.0,2,1759998769335,soft_skills
3,Leadership,Advanced,80.0,2,1759998769335,soft_skills
4,Business Analysis,Advanced,85.0,2,1759998769335,soft_skills
...,...,...,...,...,...,...
2290,DynamoDB,Intermediate,NaN,112,1771904249832,technical_skills
2291,Redis & Elasticsearch,Intermediate,NaN,112,1771904249832,technical_skills
2292,Zuora & Salesforce integrations,Intermediate,NaN,112,1771904249832,technical_skills
2293,TypeScript & Node.js,Intermediate,NaN,112,1771904249832,technical_skills
2294,React & Angular,Intermediate,NaN,112,1771904249832,technical_skills

In [44]:
df_skills_final.to_csv("dim_skills.csv", index = False)

In [45]:
pd.read_csv('dim_skills.csv')

,name,level,score,customer_id,analysis_id,skill_type
0,Collaboration,Intermediate,70.0,1,1759998111377,soft_skills
1,Problem-solving,Intermediate,70.0,1,1759998111377,soft_skills
2,Problem solving,Expert,95.0,2,1759998769335,soft_skills
3,Leadership,Advanced,80.0,2,1759998769335,soft_skills
4,Business Analysis,Advanced,85.0,2,1759998769335,soft_skills
...,...,...,...,...,...,...
2290,DynamoDB,Intermediate,NaN,112,1771904249832,technical_skills
2291,Redis & Elasticsearch,Intermediate,NaN,112,1771904249832,technical_skills
2292,Zuora & Salesforce integrations,Intermediate,NaN,112,1771904249832,technical_skills
2293,TypeScript & Node.js,Intermediate,NaN,112,1771904249832,technical_skills
2294,React & Angular,Intermediate,NaN,112,1771904249832,technical_skills